import io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

lines = [
"UPDATE words SET korean='함정, 전함', example_zh='海军的舰艇在海上巡逻，保卫海疆。', example_ko='해군 함정이 해상 순찰을 하며 해양 영토를 수호한다.' WHERE id=3149;",
"UPDATE words SET korean='거의, ~에 가깝다', example_zh='参加者将近三百人，场面热闹。', example_ko='참가자가 거의 300명에 달해 분위기가 떠들썩했다.' WHERE id=3150;",
"UPDATE words SET korean='장군', example_zh='这位将军指挥了一场著名的战役。', example_ko='이 장군은 유명한 전투를 지휘했다.' WHERE id=3151;",
"UPDATE words SET korean='굳다, 경직되다', example_zh='长时间坐着会让肌肉变得僵硬。', example_ko='오랫동안 앉아 있으면 근육이 굳어진다.' WHERE id=3152;",
"UPDATE words SET korean='노, 오어', example_zh='他用力划桨，小船快速前进。', example_ko='그는 힘껏 노를 저어 작은 배가 빠르게 나아갔다.' WHERE id=3153;",
"UPDATE words SET korean='장려하다', example_zh='公司奖励了表现优秀的员工。', example_ko='회사가 우수한 직원에게 상을 주었다.' WHERE id=3154;",
"UPDATE words SET korean='상을 주다', example_zh='他获得了比赛的奖赏，十分高兴。', example_ko='그는 경기의 상을 받아 매우 기뻐했다.' WHERE id=3155;",
"UPDATE words SET korean='내려오다, 도래하다', example_zh='夜幕降临，整座城市灯火通明。', example_ko='밤이 내려와 도시 전체가 불빛으로 환하게 빛났다.' WHERE id=3156;",
"UPDATE words SET korean='교차하다', example_zh='两条路在这里交叉。', example_ko='두 길이 이곳에서 교차한다.' WHERE id=3157;",
"UPDATE words SET korean='설명하다, 인계하다', example_zh='在离职前，他把工作交代给了同事。', example_ko='퇴직 전에 그는 업무를 동료에게 인계했다.' WHERE id=3158;",
"UPDATE words SET korean='교섭하다', example_zh='双方就价格问题进行了多轮交涉。', example_ko='양측은 가격 문제를 두고 여러 차례 교섭했다.' WHERE id=3159;",
"UPDATE words SET korean='교류하다', example_zh='他与国际学者保持密切的学术交往。', example_ko='그는 국제 학자들과 긴밀한 학술 교류를 유지한다.' WHERE id=3160;",
"UPDATE words SET korean='거래하다', example_zh='这家公司与多个国家进行贸易交易。', example_ko='이 회사는 여러 나라와 무역 거래를 한다.' WHERE id=3161;",
"UPDATE words SET korean='초점', example_zh='这件事成为了社会关注的焦点。', example_ko='이 일이 사회적 관심의 초점이 됐다.' WHERE id=3162;",
"UPDATE words SET korean='초조하다', example_zh='考试前他十分焦急，难以入睡。', example_ko='시험 전 그는 매우 초조하여 잠들기 어려웠다.' WHERE id=3163;",
"UPDATE words SET korean='응석 부리다', example_zh='她从小被溺爱，养成了娇气的性格。', example_ko='그녀는 어릴 때부터 응석을 받아줘 나약한 성격이 됐다.' WHERE id=3164;",
"UPDATE words SET korean='구석', example_zh='他躲在角落里，不想被人注意。', example_ko='그는 구석에 숨어 눈에 띄고 싶지 않았다.' WHERE id=3165;",
"UPDATE words SET korean='젓다', example_zh='做蛋糕时需要搅拌面粉和鸡蛋。', example_ko='케이크를 만들 때 밀가루와 달걀을 섞어야 한다.' WHERE id=3166;",
"UPDATE words SET korean='납부하다', example_zh='每个月需要缴纳房租和水电费。', example_ko='매달 집세와 수도 전기 요금을 납부해야 한다.' WHERE id=3167;",
"UPDATE words SET korean='교양', example_zh='一个人的教养体现在日常的言行举止中。', example_ko='사람의 교양은 일상적인 언행에서 드러난다.' WHERE id=3168;",
"UPDATE words SET korean='겨루다', example_zh='两队在决赛中进行了激烈的较量。', example_ko='두 팀이 결승전에서 치열한 겨루기를 펼쳤다.' WHERE id=3169;",
"UPDATE words SET korean='모두', example_zh='皆大欢喜，这是最好的结局。', example_ko='모두가 기뻐하니 이것이 가장 좋은 결말이다.' WHERE id=3170;",
"UPDATE words SET korean='연이어', example_zh='他接连获奖，成为全校的骄傲。', example_ko='그는 연이어 상을 받아 학교 전체의 자랑이 됐다.' WHERE id=3171;",
"UPDATE words SET korean='계층', example_zh='社会各阶层的人都参加了这次活动。', example_ko='사회 각 계층의 사람들이 이번 행사에 참여했다.' WHERE id=3172;",
"UPDATE words SET korean='폭로하다', example_zh='记者揭发了官员腐败的事实。', example_ko='기자가 관리의 부패 사실을 폭로했다.' WHERE id=3173;",
"UPDATE words SET korean='밝히다', example_zh='这本书揭露了社会的阴暗面。', example_ko='이 책은 사회의 어두운 면을 밝혔다.' WHERE id=3174;",
"UPDATE words SET korean='리듬', example_zh='生活要有节奏，不能过于紧张。', example_ko='생활에 리듬이 있어야 하며 너무 긴장해서는 안 된다.' WHERE id=3175;",
"UPDATE words SET korean='뛰어나다', example_zh='她是一位杰出的科学家，取得了很多成就。', example_ko='그녀는 뛰어난 과학자로 많은 성과를 거뒀다.' WHERE id=3176;",
"UPDATE words SET korean='결정, 결실', example_zh='多年的努力终于结晶成了一本书。', example_ko='수년간의 노력이 마침내 책 한 권의 결실을 맺었다.' WHERE id=3177;",
"UPDATE words SET korean='결말', example_zh='这个故事有一个出乎意料的结局。', example_ko='이 이야기는 예상 밖의 결말을 가지고 있다.' WHERE id=3178;",
"UPDATE words SET korean='결산하다', example_zh='月底需要对账务进行结算。', example_ko='월말에 계정을 결산해야 한다.' WHERE id=3179;",
"UPDATE words SET korean='전력을 다하다', example_zh='他竭尽全力完成了这项艰巨的任务。', example_ko='그는 전력을 다해 이 힘든 임무를 완수했다.' WHERE id=3180;",
"UPDATE words SET korean='~까지', example_zh='报名截至本月底，请抓紧时间。', example_ko='신청은 이달 말까지이니 서두르세요.' WHERE id=3181;",
"UPDATE words SET korean='해제하다', example_zh='双方同意解除合同中的某些条款。', example_ko='양측은 계약의 일부 조항을 해제하기로 합의했다.' WHERE id=3182;",
"UPDATE words SET korean='해고하다', example_zh='公司因为业绩下滑解雇了部分员工。', example_ko='회사가 실적 하락으로 일부 직원을 해고했다.' WHERE id=3183;",
"UPDATE words SET korean='해부하다', example_zh='医学生通过解剖实验学习人体结构。', example_ko='의대생이 해부 실험을 통해 인체 구조를 배운다.' WHERE id=3184;",
"UPDATE words SET korean='해산하다', example_zh='由于内部矛盾，这个团体宣布解散。', example_ko='내부 갈등으로 이 단체가 해산을 선언했다.' WHERE id=3185;",
"UPDATE words SET korean='해체하다', example_zh='苏联于1991年解体，分裂成多个国家。', example_ko='소련은 1991년에 해체되어 여러 나라로 분리됐다.' WHERE id=3186;",
"UPDATE words SET korean='참고하다', example_zh='我们可以借鉴外国的先进经验。', example_ko='우리는 외국의 선진 경험을 참고할 수 있다.' WHERE id=3187;",
"UPDATE words SET korean='~의 도움으로', example_zh='借助现代技术，这项工程得以顺利完成。', example_ko='현대 기술의 도움으로 이 공사가 순조롭게 완공됐다.' WHERE id=3188;",
"UPDATE words SET korean='경계하다', example_zh='士兵们保持着高度的戒备状态。', example_ko='병사들이 높은 경계 상태를 유지하고 있다.' WHERE id=3189;",
"UPDATE words SET korean='한계, 경계', example_zh='法律规定了行为的界限。', example_ko='법률은 행동의 한계를 규정한다.' WHERE id=3190;",
"UPDATE words SET korean='흥미진진하다', example_zh='他讲故事津津有味，孩子们听得入了迷。', example_ko='그는 이야기를 매우 재미있게 해서 아이들이 빠져들었다.' WHERE id=3191;",
"UPDATE words SET korean='금융', example_zh='金融市场的波动影响了全球经济。', example_ko='금융 시장의 변동이 세계 경제에 영향을 미쳤다.' WHERE id=3192;",
"UPDATE words SET korean='긴밀하다', example_zh='两国之间保持着紧密的合作关系。', example_ko='양국은 긴밀한 협력 관계를 유지하고 있다.' WHERE id=3193;",
"UPDATE words SET korean='긴박하다', example_zh='时间紧迫，我们必须尽快完成任务。', example_ko='시간이 긴박하여 우리는 최대한 빨리 임무를 완수해야 한다.' WHERE id=3194;",
"UPDATE words SET korean='가능한 빨리', example_zh='请尽快回复我的邮件。', example_ko='가능한 빨리 내 이메일에 회신해 주세요.' WHERE id=3195;",
"UPDATE words SET korean='밝은 미래', example_zh='只要努力，就会有锦绣前程。', example_ko='노력하기만 하면 밝은 미래가 있을 것이다.' WHERE id=3196;",
"UPDATE words SET korean='나아가', example_zh='掌握了基础知识，进而才能深入研究。', example_ko='기초 지식을 습득한 뒤 나아가 깊이 연구할 수 있다.' WHERE id=3197;",
"UPDATE words SET korean='공격하다', example_zh='军队向敌方阵地发起了进攻。', example_ko='군대가 적의 진지를 향해 공격을 가했다.' WHERE id=3198;",
"UPDATE words SET korean='진화하다', example_zh='物种通过自然选择不断进化。', example_ko='종은 자연선택을 통해 끊임없이 진화한다.' WHERE id=3199;",
"UPDATE words SET korean='진전', example_zh='经过努力，项目取得了明显进展。', example_ko='노력 끝에 프로젝트가 뚜렷한 진전을 이루었다.' WHERE id=3200;",
"UPDATE words SET korean='최근', example_zh='近来天气变化无常，要注意保暖。', example_ko='최근 날씨 변화가 심하니 따뜻하게 입어야 한다.' WHERE id=3201;",
"UPDATE words SET korean='근시', example_zh='由于长时间看手机，很多年轻人患了近视。', example_ko='오랫동안 스마트폰을 봐서 많은 젊은이들이 근시가 됐다.' WHERE id=3202;",
"UPDATE words SET korean='담그다', example_zh='他把脚浸泡在热水里，缓解了疲劳。', example_ko='그는 발을 뜨거운 물에 담가 피로를 풀었다.' WHERE id=3203;",
"UPDATE words SET korean='승진하다', example_zh='他因为工作出色而晋升为部门经理。', example_ko='그는 업무 성과가 탁월하여 부서 관리자로 승진했다.' WHERE id=3204;",
"UPDATE words SET korean='의욕, 열기', example_zh='他干什么事都有使不完的劲头。', example_ko='그는 무슨 일이든 넘치는 의욕으로 한다.' WHERE id=3205;",
"UPDATE words SET korean='줄기', example_zh='这棵植物的茎很细，但生命力很强。', example_ko='이 식물의 줄기는 가늘지만 생명력이 강하다.' WHERE id=3206;",
"UPDATE words SET korean='꼼꼼히 계산하다', example_zh='他精打细算，把每一分钱都花在刀刃上。', example_ko='그는 꼼꼼히 계산하여 모든 돈을 가장 필요한 곳에 쓴다.' WHERE id=3207;",
"UPDATE words SET korean='정수, 핵심', example_zh='这本书凝聚了作者多年研究的精华。', example_ko='이 책에는 저자의 수년간 연구의 정수가 담겨 있다.' WHERE id=3208;",
"UPDATE words SET korean='간소화하다', example_zh='公司精简了机构，提高了工作效率。', example_ko='회사가 조직을 간소화하여 업무 효율을 높였다.' WHERE id=3209;",
"UPDATE words SET korean='정밀하다', example_zh='航天技术需要精密的仪器和设备。', example_ko='우주 항공 기술에는 정밀한 기기와 설비가 필요하다.' WHERE id=3210;",
"UPDATE words SET korean='정확하다', example_zh='科学实验要求数据精确无误。', example_ko='과학 실험은 데이터가 정확해야 한다.' WHERE id=3211;",
"UPDATE words SET korean='정통하다', example_zh='他精通三门外语，工作能力很强。', example_ko='그는 세 가지 외국어에 정통하여 업무 능력이 뛰어나다.' WHERE id=3212;",
"UPDATE words SET korean='정성스럽다', example_zh='她精心准备了一顿丰盛的晚餐。', example_ko='그녀는 정성스럽게 풍성한 저녁 식사를 준비했다.' WHERE id=3213;",
"UPDATE words SET korean='끊임없이 향상을 추구하다', example_zh='工匠精益求精，把每件产品做到极致。', example_ko='장인은 끊임없이 향상을 추구하여 모든 제품을 극한까지 만든다.' WHERE id=3214;",
"UPDATE words SET korean='정교하다', example_zh='这件手工艺品做工精致，令人赞叹。', example_ko='이 공예품은 만듦새가 정교하여 탄성을 자아낸다.' WHERE id=3215;",
"UPDATE words SET korean='경비', example_zh='这次活动的经费严重不足，需要追加预算。', example_ko='이번 행사의 경비가 심각하게 부족하여 예산 추가가 필요하다.' WHERE id=3216;",
"UPDATE words SET korean='장사하다', example_zh='他放弃了铁饭碗，选择自己经商。', example_ko='그는 안정된 직업을 포기하고 직접 장사하기로 했다.' WHERE id=3217;",
"UPDATE words SET korean='경위, 경도와 위도', example_zh='他从不同经纬度分析了这个问题。', example_ko='그는 다양한 각도에서 이 문제를 분석했다.' WHERE id=3218;",
"UPDATE words SET korean='놀라게 하다', example_zh='突然的爆炸声惊动了附近的居民。', example_ko='갑작스러운 폭발 소리가 근처 주민들을 놀라게 했다.' WHERE id=3219;",
"UPDATE words SET korean='놀랍다', example_zh='他的魔术表演令观众感到惊奇。', example_ko='그의 마술 공연이 관객들을 놀라게 했다.' WHERE id=3220;",
"UPDATE words SET korean='놀라다', example_zh='听到这个消息，他感到十分惊讶。', example_ko='이 소식을 듣고 그는 매우 놀랐다.' WHERE id=3221;",
"UPDATE words SET korean='성실하고 꼼꼼하다', example_zh='他兢兢业业地工作了三十年。', example_ko='그는 성실하고 꼼꼼하게 30년간 일했다.' WHERE id=3222;",
"UPDATE words SET korean='우물', example_zh='村子里有一口古老的水井。', example_ko='마을에 오래된 우물이 하나 있다.' WHERE id=3223;",
"UPDATE words SET korean='경고하다', example_zh='医生警告他必须戒烟，否则会危及生命。', example_ko='의사는 담배를 끊지 않으면 생명이 위험하다고 경고했다.' WHERE id=3224;",
"UPDATE words SET korean='경계하다, 조심하다', example_zh='我们要对网络诈骗保持高度警惕。', example_ko='우리는 인터넷 사기에 대해 높은 경계를 유지해야 한다.' WHERE id=3225;",
"UPDATE words SET korean='경추, 목뼈', example_zh='长期低头玩手机容易导致颈椎问题。', example_ko='오랫동안 고개를 숙이고 스마트폰을 하면 경추 문제가 생기기 쉽다.' WHERE id=3226;",
"UPDATE words SET korean='경례하다', example_zh='士兵向长官敬礼，表示尊敬。', example_ko='병사가 상관에게 경례하여 존경을 표했다.' WHERE id=3227;",
"UPDATE words SET korean='경지, 경계', example_zh='他在艺术上达到了很高的境界。', example_ko='그는 예술에서 매우 높은 경지에 이르렀다.' WHERE id=3228;",
"UPDATE words SET korean='경기, 대회', example_zh='这次竞赛吸引了来自全国各地的选手。', example_ko='이번 경기에는 전국 각지의 선수들이 참가했다.' WHERE id=3229;",
"UPDATE words SET korean='선거에 출마하다', example_zh='他宣布参加总统竞选。', example_ko='그는 대통령 선거 출마를 선언했다.' WHERE id=3230;",
"UPDATE words SET korean='렌즈, 앵글', example_zh='摄影师捕捉了很多精彩的镜头。', example_ko='사진작가가 많은 멋진 앵글을 포착했다.' WHERE id=3231;",
"UPDATE words SET korean='분쟁', example_zh='两国之间的领土纠纷由来已久。', example_ko='양국 간 영토 분쟁은 오래된 일이다.' WHERE id=3232;",
"UPDATE words SET korean='시정하다', example_zh='老师帮助学生纠正了发音错误。', example_ko='선생님이 학생의 발음 실수를 바로잡아 주었다.' WHERE id=3233;",
"UPDATE words SET korean='알코올', example_zh='酒精含量过高的饮料对健康有害。', example_ko='알코올 함량이 너무 높은 음료는 건강에 해롭다.' WHERE id=3234;",
"UPDATE words SET korean='구제하다', example_zh='政府向灾区提供了救济物资。', example_ko='정부가 재난 지역에 구제 물자를 지원했다.' WHERE id=3235;",
"UPDATE words SET korean='가까운 곳에서', example_zh='他就近找了一家便利店买东西。', example_ko='그는 가까운 편의점을 찾아 물건을 샀다.' WHERE id=3236;",
"UPDATE words SET korean='취업하다', example_zh='大学生面临着就业压力越来越大的问题。', example_ko='대학생들이 점점 커지는 취업 압박 문제에 직면하고 있다.' WHERE id=3237;",
"UPDATE words SET korean='취임하다', example_zh='新市长正式就职，开始履行职责。', example_ko='새 시장이 공식 취임하여 직무를 수행하기 시작했다.' WHERE id=3238;",
"UPDATE words SET korean='허리를 굽히다', example_zh='学生向老师深深地鞠了一个躬。', example_ko='학생이 선생님께 깊이 허리를 굽혀 인사했다.' WHERE id=3239;",
"UPDATE words SET korean='구류하다', example_zh='警察将嫌疑人拘留以便进一步调查。', example_ko='경찰이 용의자를 구류하여 추가 조사를 진행했다.' WHERE id=3240;",
"UPDATE words SET korean='제약하다, 어색하다', example_zh='他在陌生人面前总是感到拘束。', example_ko='그는 낯선 사람 앞에서 항상 어색함을 느낀다.' WHERE id=3241;",
"UPDATE words SET korean='거주하다', example_zh='他在这个城市居住了二十年。', example_ko='그는 이 도시에서 20년째 거주하고 있다.' WHERE id=3242;",
"UPDATE words SET korean='부분적이다', example_zh='这场地震造成了局部地区的严重破坏。', example_ko='이 지진으로 일부 지역에 심각한 피해가 발생했다.' WHERE id=3243;",
"UPDATE words SET korean='국면, 상황', example_zh='经过谈判，双方的局面有所好转。', example_ko='협상을 거쳐 양측의 국면이 다소 개선됐다.' WHERE id=3244;",
"UPDATE words SET korean='정세, 형세', example_zh='当前的国际局势错综复杂。', example_ko='현재 국제 정세는 복잡하게 얽혀 있다.' WHERE id=3245;",
"UPDATE words SET korean='제한하다', example_zh='他的视野不应该局限于眼前的利益。', example_ko='그의 시야가 눈앞의 이익에만 국한되어서는 안 된다.' WHERE id=3246;",
"UPDATE words SET korean='행동, 거동', example_zh='他的一举一动都受到了媒体的关注。', example_ko='그의 일거수일투족이 미디어의 관심을 받았다.' WHERE id=3247;",
"UPDATE words SET korean='세계적으로 유명하다', example_zh='这位艺术家举世闻名，作品遍布全球。', example_ko='이 예술가는 세계적으로 유명하며 작품이 전 세계에 퍼져 있다.' WHERE id=3248;",
"UPDATE words SET korean='세계가 주목하다', example_zh='这项科学发现举世瞩目，引发广泛讨论。', example_ko='이 과학적 발견은 세계가 주목하여 광범위한 논의를 불러일으켰다.' WHERE id=3249;",
"UPDATE words SET korean='매우 중요하다', example_zh='他在这个项目中举足轻重，不可或缺。', example_ko='그는 이 프로젝트에서 매우 중요하여 없어서는 안 될 존재다.' WHERE id=3250;",
"UPDATE words SET korean='씹다', example_zh='老人仔细咀嚼食物，帮助消化。', example_ko='노인이 음식을 꼼꼼히 씹어 소화를 돕는다.' WHERE id=3251;",
"UPDATE words SET korean='낙담하다', example_zh='失败后他感到很沮丧，需要时间恢复。', example_ko='실패 후 그는 낙담하여 회복할 시간이 필요했다.' WHERE id=3252;",
"UPDATE words SET korean='극본, 대본', example_zh='这部电影的剧本获得了奥斯卡奖。', example_ko='이 영화의 대본은 아카데미상을 수상했다.' WHERE id=3253;",
"UPDATE words SET korean='격렬하다', example_zh='两队之间的竞争十分剧烈。', example_ko='두 팀 간의 경쟁이 매우 치열했다.' WHERE id=3254;",
"UPDATE words SET korean='정신을 집중하다', example_zh='考试时要聚精会神，不能分心。', example_ko='시험 중에는 정신을 집중해야 하며 산만해서는 안 된다.' WHERE id=3255;",
"UPDATE words SET korean='~에 따르면', example_zh='据悉，公司明年将进行大规模扩张。', example_ko='알려진 바에 따르면 회사는 내년에 대규모 확장을 진행할 예정이다.' WHERE id=3256;",
"UPDATE words SET korean='결책하다', example_zh='领导层做出了关键的决策，影响公司发展。', example_ko='지도층이 회사 발전에 영향을 미치는 핵심 결정을 내렸다.' WHERE id=3257;",
"UPDATE words SET korean='깨닫다', example_zh='他逐渐觉悟到了自己的错误。', example_ko='그는 점차 자신의 실수를 깨달았다.' WHERE id=3258;",
"UPDATE words SET korean='각성하다', example_zh='民众的觉醒推动了社会的进步。', example_ko='민중의 각성이 사회의 발전을 촉진했다.' WHERE id=3259;",
"UPDATE words SET korean='절망하다', example_zh='面对重重困难，他陷入了绝望。', example_ko='수많은 어려움에 직면하여 그는 절망에 빠졌다.' WHERE id=3260;",
"UPDATE words SET korean='군대', example_zh='军队保卫着国家的领土安全。', example_ko='군대가 국가의 영토 안전을 수호하고 있다.' WHERE id=3261;",
"UPDATE words SET korean='만화, 카툰', example_zh='孩子们都喜欢看卡通电影。', example_ko='아이들은 모두 만화 영화 보는 것을 좋아한다.' WHERE id=3262;",
"UPDATE words SET korean='채굴하다', example_zh='这个地区开采了大量的煤矿资源。', example_ko='이 지역에서 대량의 석탄 자원이 채굴됐다.' WHERE id=3263;",
"UPDATE words SET korean='제명하다', example_zh='他因违反规定被公司开除。', example_ko='그는 규정 위반으로 회사에서 제명됐다.' WHERE id=3264;",
"UPDATE words SET korean='넓다, 탁 트이다', example_zh='站在山顶，眼前的视野十分开阔。', example_ko='산꼭대기에 서니 눈앞의 시야가 매우 탁 트였다.' WHERE id=3265;",
"UPDATE words SET korean='명랑하다', example_zh='她性格开朗，总是给人带来快乐。', example_ko='그녀는 성격이 명랑하여 항상 사람들에게 즐거움을 준다.' WHERE id=3266;",
"UPDATE words SET korean='개명하다', example_zh='开明的领导善于听取下属的意见。', example_ko='개명한 지도자는 부하 직원의 의견을 잘 듣는다.' WHERE id=3267;",
"UPDATE words SET korean='개척하다', example_zh='他们开辟了一条新的贸易路线。', example_ko='그들은 새로운 무역 경로를 개척했다.' WHERE id=3268;",
"UPDATE words SET korean='끓인 물', example_zh='中国人习惯喝开水，认为有助于健康。', example_ko='중국인은 끓인 물을 마시는 습관이 있으며 건강에 좋다고 생각한다.' WHERE id=3269;",
"UPDATE words SET korean='개척하다, 확장하다', example_zh='公司不断开拓新的市场。', example_ko='회사가 계속 새로운 시장을 개척하고 있다.' WHERE id=3270;",
"UPDATE words SET korean='전개하다', example_zh='学校开展了一系列文化活动。', example_ko='학교가 일련의 문화 활동을 전개했다.' WHERE id=3271;",
"UPDATE words SET korean='지출', example_zh='家庭的开支要合理规划，避免浪费。', example_ko='가정의 지출은 합리적으로 계획하여 낭비를 피해야 한다.' WHERE id=3272;",
"UPDATE words SET korean='게재하다', example_zh='这篇文章被刊登在著名的学术杂志上。', example_ko='이 글이 유명 학술지에 게재됐다.' WHERE id=3273;",
"UPDATE words SET korean='간행물', example_zh='这家出版社出版了很多优秀的刊物。', example_ko='이 출판사는 많은 우수한 간행물을 출판했다.' WHERE id=3274;",
"UPDATE words SET korean='탐사하다', example_zh='地质学家在山区勘探矿产资源。', example_ko='지질학자들이 산간 지역에서 광물 자원을 탐사했다.' WHERE id=3275;",
"UPDATE words SET korean='여기다, 대우하다', example_zh='要平等地看待每一个人。', example_ko='모든 사람을 평등하게 대우해야 한다.' WHERE id=3276;",
"UPDATE words SET korean='방문하다', example_zh='他去医院看望了生病的老朋友。', example_ko='그는 병원에 가서 아픈 오랜 친구를 문병했다.' WHERE id=3277;",
"UPDATE words SET korean='관대하다', example_zh='他对朋友十分慷慨，愿意分享自己的东西。', example_ko='그는 친구에게 매우 관대하여 자신의 것을 기꺼이 나눈다.' WHERE id=3278;",
"UPDATE words SET korean='어깨에 메다', example_zh='他扛着一袋大米走上了楼梯。', example_ko='그는 쌀 한 포대를 어깨에 메고 계단을 올랐다.' WHERE id=3279;",
"UPDATE words SET korean='시찰하다', example_zh='代表团前往工厂进行实地考察。', example_ko='대표단이 공장을 현지 시찰했다.' WHERE id=3280;",
"UPDATE words SET korean='고고학', example_zh='考古学家在这里发现了古代文明的遗址。', example_ko='고고학자들이 이곳에서 고대 문명의 유적을 발견했다.' WHERE id=3281;",
"UPDATE words SET korean='심사하다', example_zh='公司定期对员工进行绩效考核。', example_ko='회사가 정기적으로 직원 업무 실적을 심사한다.' WHERE id=3282;",
"UPDATE words SET korean='시험하다, 시련', example_zh='这次危机是对他们团队精神的一次考验。', example_ko='이번 위기는 그들의 팀 정신에 대한 시련이다.' WHERE id=3283;",
"UPDATE words SET korean='접근하다', example_zh='大家靠拢在一起，准备出发。', example_ko='모두가 가까이 모여 출발 준비를 했다.' WHERE id=3284;",
"UPDATE words SET korean='두드리다', example_zh='他不小心磕到了桌角，很疼。', example_ko='그는 실수로 책상 모서리에 부딪혀 매우 아팠다.' WHERE id=3285;",
"UPDATE words SET korean='알갱이', example_zh='一颗颗饱满的颗粒代表了丰收的希望。', example_ko='알알이 꽉 찬 낟알이 풍작의 희망을 나타낸다.' WHERE id=3286;",
"UPDATE words SET korean='과목', example_zh='他最喜欢的科目是数学和物理。', example_ko='그가 가장 좋아하는 과목은 수학과 물리다.' WHERE id=3287;",
"UPDATE words SET korean='갈망하다', example_zh='他渴望自由，希望摆脱束缚。', example_ko='그는 자유를 갈망하며 속박에서 벗어나고 싶어 한다.' WHERE id=3288;",
"UPDATE words SET korean='상당하다', example_zh='这次活动的参与人数相当可观。', example_ko='이번 행사의 참여 인원이 상당하다.' WHERE id=3289;",
"UPDATE words SET korean='맛있다', example_zh='这家餐厅的菜味道可口，深受顾客喜爱。', example_ko='이 식당의 음식은 맛있어서 고객들에게 인기가 많다.' WHERE id=3290;",
"UPDATE words SET korean='가증스럽다', example_zh='他的行为实在可恶，让人忍无可忍。', example_ko='그의 행동은 정말 가증스러워 참을 수가 없다.' WHERE id=3291;",
"UPDATE words SET korean='우습다', example_zh='他的借口实在可笑，没人相信。', example_ko='그의 변명은 정말 우스워서 아무도 믿지 않는다.' WHERE id=3292;",
"UPDATE words SET korean='실행 가능하다', example_zh='这个方案在技术上是可行的。', example_ko='이 방안은 기술적으로 실행 가능하다.' WHERE id=3293;",
"UPDATE words SET korean='일각을 다투다', example_zh='病人的情况危急，救治刻不容缓。', example_ko='환자 상태가 위급하여 치료가 시급하다.' WHERE id=3294;",
"UPDATE words SET korean='과제, 주제', example_zh='解决贫困问题是当今世界的重要课题。', example_ko='빈곤 문제 해결은 오늘날 세계의 중요한 과제다.' WHERE id=3295;",
"UPDATE words SET korean='고객', example_zh='公司非常重视客户的需求和反馈。', example_ko='회사는 고객의 요구와 피드백을 매우 중시한다.' WHERE id=3296;",
"UPDATE words SET korean='갉아먹다', example_zh='老鼠啃坏了家里的木制家具。', example_ko='쥐가 집의 나무 가구를 갉아먹었다.' WHERE id=3297;",
"UPDATE words SET korean='간절하다', example_zh='他用恳切的语言表达了自己的想法。', example_ko='그는 간절한 말로 자신의 생각을 표현했다.' WHERE id=3298;",
"UPDATE words SET korean='구덩이', example_zh='工人挖了一个深坑，准备埋管道。', example_ko='노동자가 깊은 구덩이를 파서 관을 묻을 준비를 했다.' WHERE id=3299;",
"UPDATE words SET korean='공허하다', example_zh='这篇文章内容空洞，缺乏实质内容。', example_ko='이 글은 내용이 공허하여 실질적인 내용이 부족하다.' WHERE id=3300;",
"UPDATE words SET korean='전무후무하다', example_zh='这场演出空前绝后，令观众叹为观止。', example_ko='이 공연은 전무후무하여 관객들의 탄성을 자아냈다.' WHERE id=3301;",
"UPDATE words SET korean='공상하다', example_zh='他喜欢空想，却不付诸实践。', example_ko='그는 공상을 좋아하지만 실천에 옮기지 않는다.' WHERE id=3302;",
"UPDATE words SET korean='공허하다, 허전하다', example_zh='整天无所事事让他感到空虚。', example_ko='하루 종일 아무것도 하지 않으니 그는 허전함을 느꼈다.' WHERE id=3303;",
"UPDATE words SET korean='구멍', example_zh='这件衣服上有一个小孔，需要修补。', example_ko='이 옷에 작은 구멍이 있어 수선이 필요하다.' WHERE id=3304;",
"UPDATE words SET korean='위협하다', example_zh='他受到了歹徒的恐吓，不敢报警。', example_ko='그는 불량배의 위협을 받아 신고하지 못했다.' WHERE id=3305;",
"UPDATE words SET korean='공포', example_zh='黑暗中他感到了一种莫名的恐惧。', example_ko='어둠 속에서 그는 알 수 없는 공포를 느꼈다.' WHERE id=3306;",
"UPDATE words SET korean='공백', example_zh='这段历史有很多空白，需要进一步研究。', example_ko='이 역사에는 많은 공백이 있어 추가 연구가 필요하다.' WHERE id=3307;",
"UPDATE words SET korean='틈새', example_zh='他从门缝的空隙中看到了外面的情况。', example_ko='그는 문틈의 틈새로 바깥 상황을 보았다.' WHERE id=3308;",
"UPDATE words SET korean='말투, 어조', example_zh='他说话的口气很强硬，让人难以接受。', example_ko='그의 말투가 매우 강경하여 받아들이기 어렵다.' WHERE id=3309;",
"UPDATE words SET korean='구강', example_zh='保持口腔卫生对健康非常重要。', example_ko='구강 위생을 유지하는 것은 건강에 매우 중요하다.' WHERE id=3310;",
"UPDATE words SET korean='구두의', example_zh='他做出了口头承诺，但没有书面证明。', example_ko='그는 구두 약속을 했지만 서면 증거가 없다.' WHERE id=3311;",
"UPDATE words SET korean='사투리, 억양', example_zh='他说话有浓重的地方口音。', example_ko='그는 말할 때 강한 지방 억양이 있다.' WHERE id=3312;",
"UPDATE words SET korean='고갈되다', example_zh='地下水资源正在逐渐枯竭。', example_ko='지하수 자원이 점차 고갈되고 있다.' WHERE id=3313;",
"UPDATE words SET korean='지루하다', example_zh='这份工作单调枯燥，没有什么挑战性。', example_ko='이 일은 단조롭고 지루하며 도전성이 없다.' WHERE id=3314;",
"UPDATE words SET korean='고생 끝에 낙이 온다', example_zh='苦尽甘来，他终于实现了自己的梦想。', example_ko='고생 끝에 낙이 와서 그는 마침내 꿈을 이루었다.' WHERE id=3315;",
"UPDATE words SET korean='걸치다, 들다', example_zh='她挎着一个精致的手提包出门了。', example_ko='그녀는 정교한 핸드백을 들고 나갔다.' WHERE id=3316;",
"UPDATE words SET korean='넘다', example_zh='他轻松地跨过了障碍物。', example_ko='그는 장애물을 가볍게 넘었다.' WHERE id=3317;",
"UPDATE words SET korean='쾌활하다', example_zh='他性格快活，总是笑口常开。', example_ko='그는 성격이 쾌활하여 항상 웃음이 끊이지 않는다.' WHERE id=3318;",
"UPDATE words SET korean='넓다, 널찍하다', example_zh='新家宽敞明亮，住起来很舒适。', example_ko='새집이 넓고 밝아 살기가 매우 편안하다.' WHERE id=3319;",
"UPDATE words SET korean='접대하다', example_zh='主人款待了远道而来的客人。', example_ko='주인이 멀리서 온 손님을 환대했다.' WHERE id=3320;",
"UPDATE words SET korean='스타일', example_zh='这件衣服款式新颖，很受年轻人喜爱。', example_ko='이 옷은 스타일이 참신하여 젊은이들에게 인기가 많다.' WHERE id=3321;",
"UPDATE words SET korean='바구니', example_zh='她用竹筐装满了新鲜的蔬菜。', example_ko='그녀는 대나무 바구니에 신선한 채소를 가득 담았다.' WHERE id=3322;",
"UPDATE words SET korean='무단결석하다', example_zh='他经常旷课，学习成绩一落千丈。', example_ko='그는 자주 무단결석하여 성적이 급격히 떨어졌다.' WHERE id=3323;",
"UPDATE words SET korean='프레임, 틀', example_zh='我们需要建立一个完善的管理框架。', example_ko='우리는 완전한 관리 프레임을 구축해야 한다.' WHERE id=3324;",
"UPDATE words SET korean='게다가', example_zh='他不仅聪明，况且还很勤奋。', example_ko='그는 똑똑할 뿐만 아니라 게다가 매우 부지런하다.' WHERE id=3325;",
"UPDATE words SET korean='홀대하다', example_zh='不能亏待为公司付出的员工。', example_ko='회사를 위해 헌신한 직원을 홀대해서는 안 된다.' WHERE id=3326;",
"UPDATE words SET korean='손실', example_zh='公司连续亏损，面临倒闭的危机。', example_ko='회사가 연속 손실을 내어 도산 위기에 처해 있다.' WHERE id=3327;",
"UPDATE words SET korean='곤충', example_zh='昆虫在生态系统中扮演着重要的角色。', example_ko='곤충은 생태계에서 중요한 역할을 한다.' WHERE id=3328;",
"UPDATE words SET korean='묶다', example_zh='他把行李捆绑好，准备出发。', example_ko='그는 짐을 묶어 출발 준비를 했다.' WHERE id=3329;",
"UPDATE words SET korean='확충하다', example_zh='学校扩充了图书馆的藏书量。', example_ko='학교가 도서관의 장서량을 확충했다.' WHERE id=3330;",
"UPDATE words SET korean='확산하다', example_zh='火灾迅速扩散，消防员及时赶到控制了火势。', example_ko='화재가 빠르게 확산됐지만 소방관이 제때 도착해 불길을 잡았다.' WHERE id=3331;",
"UPDATE words SET korean='팽창하다', example_zh='这个城市不断扩张，人口持续增加。', example_ko='이 도시는 계속 확장하며 인구가 지속적으로 늘고 있다.' WHERE id=3332;",
"UPDATE words SET korean='나팔', example_zh='乐队里有一名吹喇叭的音乐家。', example_ko='악단에 나팔 부는 음악가가 있다.' WHERE id=3333;",
"UPDATE words SET korean='~야 (어기조사)', example_zh='这件事啦，你别担心啦。', example_ko='이 일이야, 걱정 말아.' WHERE id=3334;",
"UPDATE words SET korean='내력, 유래', example_zh='这个古老习俗的来历可以追溯到几千年前。', example_ko='이 오랜 풍습의 유래는 수천 년 전으로 거슬러 올라간다.' WHERE id=3335;",
"UPDATE words SET korean='출처', example_zh='这篇文章的信息来源可靠，有据可查。', example_ko='이 글의 정보 출처는 신뢰할 수 있으며 근거가 있다.' WHERE id=3336;",
"UPDATE words SET korean='칼럼, 항목', example_zh='这个电视台有多个不同的栏目。', example_ko='이 방송국에는 여러 가지 다양한 칼럼이 있다.' WHERE id=3337;",
"UPDATE words SET korean='게으르다', example_zh='懒惰的人很难取得成功。', example_ko='게으른 사람은 성공하기 어렵다.' WHERE id=3338;",
"UPDATE words SET korean='낭패스럽다', example_zh='他处于狼狈的境地，不知如何是好。', example_ko='그는 낭패스러운 상황에 처하여 어떻게 해야 할지 몰랐다.' WHERE id=3339;",
"UPDATE words SET korean='소리 내어 읽다', example_zh='老师让学生朗读课文，练习发音。', example_ko='선생님이 학생에게 교재를 소리 내어 읽게 하여 발음을 연습시켰다.' WHERE id=3340;",
"UPDATE words SET korean='건지다', example_zh='他从水里捞出了一条大鱼。', example_ko='그는 물속에서 큰 물고기를 건져 올렸다.' WHERE id=3341;",
"UPDATE words SET korean='잔소리하다', example_zh='他整天唠叨个不停，让人烦透了。', example_ko='그는 하루 종일 잔소리를 멈추지 않아 사람을 지치게 한다.' WHERE id=3342;",
"UPDATE words SET korean='단단하다', example_zh='这座桥的基础非常牢固，可以承受重压。', example_ko='이 다리의 기초는 매우 견고하여 큰 압력을 견딜 수 있다.' WHERE id=3343;",
"UPDATE words SET korean='불평', example_zh='他总是满腹牢骚，对什么都不满意。', example_ko='그는 항상 불만이 가득하여 어떤 것도 만족하지 못한다.' WHERE id=3344;",
"UPDATE words SET korean='즐거움', example_zh='读书是他生活中最大的乐趣。', example_ko='독서는 그의 생활 중 가장 큰 즐거움이다.' WHERE id=3345;",
"UPDATE words SET korean='기꺼이 하다', example_zh='他乐意帮助有困难的人。', example_ko='그는 어려움에 처한 사람을 기꺼이 돕는다.' WHERE id=3346;",
"UPDATE words SET korean='레이더', example_zh='雷达能够探测到远处的飞机。', example_ko='레이더는 멀리 있는 비행기를 탐지할 수 있다.' WHERE id=3347;",
"UPDATE words SET korean='비슷하다', example_zh='这两种疾病的症状十分类似。', example_ko='이 두 질병의 증상은 매우 유사하다.' WHERE id=3348;",
"UPDATE words SET korean='냉담하다', example_zh='他对陌生人的态度十分冷淡。', example_ko='그는 낯선 사람에 대한 태도가 매우 냉담하다.' WHERE id=3349;",
"UPDATE words SET korean='냉혹하다', example_zh='他是一个冷酷无情的人，从不考虑别人的感受。', example_ko='그는 냉혹무정한 사람으로 다른 사람의 감정을 전혀 고려하지 않는다.' WHERE id=3350;",
"UPDATE words SET korean='식히다', example_zh='机器运行一段时间后需要冷却。', example_ko='기계는 일정 시간 작동 후 냉각이 필요하다.' WHERE id=3351;",
"UPDATE words SET korean='멍하다', example_zh='他突然愣住了，不知道该说什么。', example_ko='그는 갑자기 멍해져서 무슨 말을 해야 할지 몰랐다.' WHERE id=3352;",
"UPDATE words SET korean='여명, 새벽', example_zh='黎明时分，东方天空泛出了红霞。', example_ko='여명 무렵 동쪽 하늘에 붉은 노을이 퍼졌다.' WHERE id=3353;",
"UPDATE words SET korean='이정표', example_zh='这项成就成为了科技发展的里程碑。', example_ko='이 성취는 과학 기술 발전의 이정표가 됐다.' WHERE id=3354;",
"UPDATE words SET korean='예의, 예절', example_zh='在正式场合，遵守礼节是非常重要的。', example_ko='공식 석상에서 예절을 지키는 것은 매우 중요하다.' WHERE id=3355;",
"UPDATE words SET korean='상대하다', example_zh='他对别人的意见根本不理睬。', example_ko='그는 다른 사람의 의견을 전혀 상대하지 않는다.' WHERE id=3356;",
"UPDATE words SET korean='당연하다', example_zh='他认为这一切都是理所当然的。', example_ko='그는 이 모든 것이 당연하다고 생각한다.' WHERE id=3357;",
"UPDATE words SET korean='당당하다', example_zh='他理直气壮地为自己辩护。', example_ko='그는 당당하게 자신을 변호했다.' WHERE id=3358;",
"UPDATE words SET korean='이성', example_zh='遇到问题要保持理智，不能冲动。', example_ko='문제에 부딪혔을 때 이성을 유지해야 하며 충동적이어서는 안 된다.' WHERE id=3359;",
"UPDATE words SET korean='입장', example_zh='在谈判中，双方都坚持了自己的立场。', example_ko='협상에서 양측이 모두 자신의 입장을 고수했다.' WHERE id=3360;",
"UPDATE words SET korean='고가도로, 인터체인지', example_zh='城市中的立交桥有效缓解了交通拥堵。', example_ko='도시의 고가도로가 교통 체증을 효과적으로 완화했다.' WHERE id=3361;",
"UPDATE words SET korean='입체적이다', example_zh='这幅画运用了立体的表现手法。', example_ko='이 그림은 입체적인 표현 기법을 사용했다.' WHERE id=3362;",
"UPDATE words SET korean='기반을 두다', example_zh='只有立足实际，才能制定出有效的方案。', example_ko='실제에 기반을 두어야만 효과적인 방안을 세울 수 있다.' WHERE id=3363;",
"UPDATE words SET korean='역대', example_zh='历代帝王都对这座宫殿进行了修缮。', example_ko='역대 황제들이 모두 이 궁전을 보수했다.' WHERE id=3364;",
"UPDATE words SET korean='예로부터', example_zh='历来，勤劳是中华民族的传统美德。', example_ko='예로부터 근면은 중화 민족의 전통적인 미덕이다.' WHERE id=3365;",
"UPDATE words SET korean='이해득실', example_zh='他权衡了利害关系，做出了最佳决策。', example_ko='그는 이해득실을 따져 최선의 결정을 내렸다.' WHERE id=3366;",
"UPDATE words SET korean='이자율', example_zh='银行降低了贷款利率，刺激经济发展。', example_ko='은행이 대출 이자율을 낮춰 경제 발전을 촉진했다.' WHERE id=3367;",
"UPDATE words SET korean='능력껏 하다', example_zh='我会力所能及地帮助有需要的人。', example_ko='나는 능력껏 도움이 필요한 사람을 도울 것이다.' WHERE id=3368;",
"UPDATE words SET korean='힘써 도모하다', example_zh='他力图在有限的时间内完成任务。', example_ko='그는 제한된 시간 안에 임무를 완수하려고 힘썼다.' WHERE id=3369;",
"UPDATE words SET korean='쟁취하다', example_zh='我们要力争在规定时间内完成任务。', example_ko='우리는 규정된 시간 안에 임무를 완수하기 위해 힘써야 한다.' WHERE id=3370;",
"UPDATE words SET korean='예외', example_zh='规则对任何人都适用，没有例外。', example_ko='규칙은 누구에게나 적용되며 예외가 없다.' WHERE id=3371;",
"UPDATE words SET korean='연달아 여러 해', example_zh='这个地区连年丰收，农民生活富裕。', example_ko='이 지역은 연달아 여러 해 풍작으로 농민 생활이 풍요롭다.' WHERE id=3372;",
"UPDATE words SET korean='연쇄', example_zh='这家公司在全国建立了连锁店。', example_ko='이 회사는 전국에 체인점을 구축했다.' WHERE id=3373;",
"UPDATE words SET korean='~와 함께', example_zh='连同这份报告，请将相关资料一并提交。', example_ko='이 보고서와 함께 관련 자료도 같이 제출해 주세요.' WHERE id=3374;",
"UPDATE words SET korean='함께 즐기다', example_zh='春节前夕，全公司员工联欢庆祝。', example_ko='춘절 전날 회사 전 직원이 함께 즐겼다.' WHERE id=3375;",
"UPDATE words SET korean='연락하다', example_zh='我们需要与合作伙伴保持密切联络。', example_ko='우리는 협력 파트너와 긴밀한 연락을 유지해야 한다.' WHERE id=3376;",
"UPDATE words SET korean='동맹', example_zh='两国结成了军事联盟，共同抵御外敌。', example_ko='두 나라가 군사 동맹을 맺어 함께 외적을 막는다.' WHERE id=3377;",
"UPDATE words SET korean='연상하다', example_zh='看到这幅画，他自然联想到了故乡。', example_ko='이 그림을 보자 그는 자연스럽게 고향을 연상했다.' WHERE id=3378;",
"UPDATE words SET korean='청렴하다', example_zh='廉洁的官员受到人民的爱戴和尊敬。', example_ko='청렴한 관리는 국민의 사랑과 존경을 받는다.' WHERE id=3379;",
"UPDATE words SET korean='양심', example_zh='他凭着良心做出了正确的选择。', example_ko='그는 양심에 따라 올바른 선택을 했다.' WHERE id=3380;",
"UPDATE words SET korean='말리다', example_zh='她把洗完的衣服晾在阳台上晒干。', example_ko='그녀는 세탁한 옷을 발코니에 널어 말렸다.' WHERE id=3381;",
"UPDATE words SET korean='양해하다', example_zh='他原谅了朋友的过失，两人和好如初。', example_ko='그는 친구의 잘못을 양해하여 둘은 예전처럼 화해했다.' WHERE id=3382;",
"UPDATE words SET korean='드넓다', example_zh='中国的西部地区辽阔无边，资源丰富。', example_ko='중국 서부 지역은 드넓고 자원이 풍부하다.' WHERE id=3383;",
"UPDATE words SET korean='열거하다', example_zh='他列举了许多例子来支持自己的论点。', example_ko='그는 자신의 주장을 뒷받침하기 위해 많은 예를 열거했다.' WHERE id=3384;",
"UPDATE words SET korean='뿌리다, 맞다', example_zh='他淋了一场雨，全身湿透了。', example_ko='그는 비를 맞아 온몸이 흠뻑 젖었다.' WHERE id=3385;",
"UPDATE words SET korean='임상', example_zh='新药需要经过严格的临床试验才能上市。', example_ko='신약은 엄격한 임상 시험을 거쳐야 시판될 수 있다.' WHERE id=3386;",
"UPDATE words SET korean='인색하다', example_zh='他为人吝啬，不愿意帮助他人。', example_ko='그는 인색하여 다른 사람을 도우려 하지 않는다.' WHERE id=3387;",
"UPDATE words SET korean='드문드문', example_zh='院子里零星地开着几朵野花。', example_ko='마당에 야생화가 드문드문 피어 있다.' WHERE id=3388;",
"UPDATE words SET korean='새벽', example_zh='凌晨时分，城市一片寂静。', example_ko='새벽 무렵 도시는 조용하기만 했다.' WHERE id=3389;",
"UPDATE words SET korean='영감', example_zh='这次旅行给了他很多创作灵感。', example_ko='이번 여행이 그에게 많은 창작 영감을 주었다.' WHERE id=3390;",
"UPDATE words SET korean='영혼', example_zh='音乐触动了人们的灵魂深处。', example_ko='음악이 사람들의 영혼 깊은 곳을 건드렸다.' WHERE id=3391;",
"UPDATE words SET korean='예민하다', example_zh='这台仪器非常灵敏，能检测出微小变化。', example_ko='이 기기는 매우 예민하여 미세한 변화를 감지할 수 있다.' WHERE id=3392;",
"UPDATE words SET korean='영리하다', example_zh='这个孩子伶俐可爱，深受大家喜爱。', example_ko='이 아이는 영리하고 귀여워 모두의 사랑을 받는다.' WHERE id=3393;",
"UPDATE words SET korean='이해하다', example_zh='他领会了老师的意思，按要求完成了任务。', example_ko='그는 선생님의 뜻을 이해하여 요구에 따라 임무를 완수했다.' WHERE id=3394;",
"UPDATE words SET korean='영사관', example_zh='他在中国驻韩领事馆办理了签证手续。', example_ko='그는 주한 중국 영사관에서 비자 수속을 밟았다.' WHERE id=3395;",
"UPDATE words SET korean='영토', example_zh='保卫国家领土的完整是军人的职责。', example_ko='국가 영토의 완전성을 수호하는 것은 군인의 직책이다.' WHERE id=3396;",
"UPDATE words SET korean='깨닫다, 터득하다', example_zh='他领悟到了人生的真谛。', example_ko='그는 인생의 진리를 터득했다.' WHERE id=3397;",
"UPDATE words SET korean='앞서다', example_zh='这家公司在技术创新方面一直领先于同行。', example_ko='이 회사는 기술 혁신 면에서 항상 동종 업계보다 앞서 있다.' WHERE id=3398;",
"UPDATE words SET korean='지도자', example_zh='这位领袖带领人民走向了繁荣富强。', example_ko='이 지도자가 국민을 이끌어 번영과 강성의 길로 나아갔다.' WHERE id=3399;",
"UPDATE words SET korean='살금살금 가다', example_zh='他溜出了教室，去操场玩耍。', example_ko='그는 교실에서 살금살금 빠져나가 운동장에서 놀았다.' WHERE id=3400;",
"UPDATE words SET korean='미련을 가지다', example_zh='他对过去的生活依然留恋，难以忘怀。', example_ko='그는 과거의 생활에 여전히 미련을 가져 잊지 못한다.' WHERE id=3401;",
"UPDATE words SET korean='기념으로 간직하다', example_zh='他们拍了照片留念，记录这美好时刻。', example_ko='그들은 이 아름다운 순간을 기념하기 위해 사진을 찍었다.' WHERE id=3402;",
"UPDATE words SET korean='조심하다', example_zh='走夜路要留神，注意安全。', example_ko='밤길을 걸을 때는 조심하여 안전에 주의해야 한다.' WHERE id=3403;",
"UPDATE words SET korean='방랑하다', example_zh='他年轻时四处流浪，见识了很多地方。', example_ko='그는 젊었을 때 여기저기 방랑하며 많은 곳을 경험했다.' WHERE id=3404;",
"UPDATE words SET korean='드러나다', example_zh='她的眼神流露出了深深的忧愁。', example_ko='그녀의 눈빛에서 깊은 근심이 드러났다.' WHERE id=3405;",
"UPDATE words SET korean='건달', example_zh='他年轻时曾经是个流氓，后来改邪归正。', example_ko='그는 젊었을 때 건달이었지만 나중에 개과천선했다.' WHERE id=3406;",
"UPDATE words SET korean='유통되다', example_zh='商品需要通过市场流通才能到达消费者手中。', example_ko='상품은 시장 유통을 통해 소비자에게 전달된다.' WHERE id=3407;",
"UPDATE words SET korean='농아', example_zh='学校为聋哑学生提供了专业的手语教育。', example_ko='학교는 농아 학생에게 전문 수어 교육을 제공했다.' WHERE id=3408;",
"UPDATE words SET korean='성대하다', example_zh='这次晚会举办得十分隆重，嘉宾云集。', example_ko='이번 만찬은 매우 성대하게 열려 귀빈들이 운집했다.' WHERE id=3409;",
"UPDATE words SET korean='독점하다', example_zh='大公司试图垄断市场，引发了反垄断调查。', example_ko='대기업이 시장을 독점하려 해 반독점 조사가 시작됐다.' WHERE id=3410;",
"UPDATE words SET korean='뒤덮다', example_zh='浓雾笼罩了整座城市，能见度极低。', example_ko='짙은 안개가 도시 전체를 뒤덮어 가시도가 매우 낮았다.' WHERE id=3411;",
"UPDATE words SET korean='끌어안다', example_zh='妈妈紧紧地搂住了孩子，不肯放手。', example_ko='엄마가 아이를 꼭 끌어안고 놓지 않았다.' WHERE id=3412;",
"UPDATE words SET korean='부엌 화덕', example_zh='农村老屋里还保留着传统的炉灶。', example_ko='농촌 옛 집에는 여전히 전통적인 부엌 화덕이 남아 있다.' WHERE id=3413;",
"UPDATE words SET korean='선박', example_zh='轮船缓缓地驶出了港口。', example_ko='선박이 천천히 항구를 빠져나갔다.' WHERE id=3414;",
"UPDATE words SET korean='윤곽', example_zh='在雾中，远处山峰的轮廓隐约可见。', example_ko='안개 속에서 멀리 산봉우리의 윤곽이 희미하게 보였다.' WHERE id=3415;",
"UPDATE words SET korean='타이어', example_zh='汽车轮胎破了，需要更换。', example_ko='자동차 타이어가 펑크났으니 교체해야 한다.' WHERE id=3416;",
"UPDATE words SET korean='포럼', example_zh='这个网络论坛吸引了很多用户参与讨论。', example_ko='이 온라인 포럼이 많은 사용자를 끌어들여 토론에 참여하게 했다.' WHERE id=3417;",
"UPDATE words SET korean='논증하다', example_zh='他用充分的证据论证了自己的观点。', example_ko='그는 충분한 증거로 자신의 견해를 입증했다.' WHERE id=3418;",
"UPDATE words SET korean='수다스럽다', example_zh='他说话啰唆，让人听不下去。', example_ko='그는 말이 수다스러워 듣기 힘들다.' WHERE id=3419;",
"UPDATE words SET korean='나사못', example_zh='需要用螺丝钉把这两块木板固定在一起。', example_ko='나사못으로 이 두 나무판을 고정해야 한다.' WHERE id=3420;",
"UPDATE words SET korean='낙성되다, 준공하다', example_zh='新图书馆正式落成，向市民开放。', example_ko='새 도서관이 공식 준공되어 시민들에게 개방됐다.' WHERE id=3421;",
"UPDATE words SET korean='실현하다', example_zh='政府承诺要将这些政策落实到位。', example_ko='정부는 이 정책들을 철저히 실현하겠다고 약속했다.' WHERE id=3422;",
"UPDATE words SET korean='줄줄이 끊이지 않다', example_zh='节假日期间，游客络绎不绝地涌入景区。', example_ko='명절 기간에 관광객이 줄줄이 관광지로 몰려들었다.' WHERE id=3423;",
"UPDATE words SET korean='여러 번', example_zh='他屡次违规，最终被公司开除。', example_ko='그는 여러 번 규정을 어기다가 결국 회사에서 해고됐다.' WHERE id=3424;",
"UPDATE words SET korean='이행하다', example_zh='他认真履行了自己的职责。', example_ko='그는 자신의 직책을 성실히 이행했다.' WHERE id=3425;",
"UPDATE words SET korean='약탈하다', example_zh='战争中，侵略者掠夺了大量文化遗产。', example_ko='전쟁 중 침략자들이 대량의 문화유산을 약탈했다.' WHERE id=3426;",
"UPDATE words SET korean='약간', example_zh='他的病情略微有所好转。', example_ko='그의 병세가 약간 나아졌다.' WHERE id=3427;",
"UPDATE words SET korean='마비시키다', example_zh='网络攻击麻痹了整个通信系统。', example_ko='사이버 공격이 통신 시스템 전체를 마비시켰다.' WHERE id=3428;",
"UPDATE words SET korean='무감각하다', example_zh='长期的孤独使他对感情变得麻木。', example_ko='오랜 고독이 그를 감정에 무감각하게 만들었다.' WHERE id=3429;",
"UPDATE words SET korean='마취하다', example_zh='手术前医生给患者进行了全身麻醉。', example_ko='수술 전 의사가 환자에게 전신 마취를 했다.' WHERE id=3430;",
"UPDATE words SET korean='부두', example_zh='工人们在码头装卸货物。', example_ko='노동자들이 부두에서 화물을 싣고 내렸다.' WHERE id=3431;",
"UPDATE words SET korean='~잖아 (어기조사)', example_zh='你知道嘛，这件事很重要。', example_ko='알잖아, 이 일은 매우 중요해.' WHERE id=3432;",
"UPDATE words SET korean='매복하다', example_zh='士兵们在山谷中埋伏，等待敌人进入。', example_ko='병사들이 계곡에 매복하여 적이 들어오기를 기다렸다.' WHERE id=3433;",
"UPDATE words SET korean='묻혀버리다', example_zh='他的才华被埋没了，未能得到充分发挥。', example_ko='그의 재능이 묻혀버려 충분히 발휘되지 못했다.' WHERE id=3434;",
"UPDATE words SET korean='매장하다', example_zh='老人被安葬在家乡的土地上。', example_ko='노인은 고향 땅에 매장됐다.' WHERE id=3435;",
"UPDATE words SET korean='내딛다', example_zh='他迈出了人生中最重要的一步。', example_ko='그는 인생에서 가장 중요한 한 걸음을 내딛었다.' WHERE id=3436;",
"UPDATE words SET korean='맥박', example_zh='医生检查了病人的脉搏，情况稳定。', example_ko='의사가 환자의 맥박을 확인하니 상태가 안정됐다.' WHERE id=3437;",
"UPDATE words SET korean='원망하다', example_zh='他埋怨天气太差，影响了心情。', example_ko='그는 날씨가 너무 나쁘다고 원망하며 기분이 안 좋아졌다.' WHERE id=3438;",
"UPDATE words SET korean='만성적이다', example_zh='他患有慢性病，需要长期服药。', example_ko='그는 만성 질환을 앓고 있어 장기적으로 약을 복용해야 한다.' WHERE id=3439;",
"UPDATE words SET korean='길다, 오래 끌다', example_zh='漫长的等待终于结束了，他见到了盼望已久的人。', example_ko='길고 오랜 기다림이 마침내 끝나 그는 오랫동안 기다리던 사람을 만났다.' WHERE id=3440;",
"UPDATE words SET korean='만화', example_zh='他从小就喜欢看漫画书。', example_ko='그는 어릴 때부터 만화책 보기를 좋아했다.' WHERE id=3441;",
"UPDATE words SET korean='만연하다', example_zh='谣言在网上迅速蔓延，引发了恐慌。', example_ko='소문이 인터넷에서 빠르게 퍼져 공황을 불러일으켰다.' WHERE id=3442;",
"UPDATE words SET korean='바쁘다', example_zh='他每天忙碌于各种工作事务中。', example_ko='그는 매일 각종 업무로 바쁘게 지낸다.' WHERE id=3443;",
"UPDATE words SET korean='아득히 넓다', example_zh='走进沙漠，眼前是茫茫无际的黄沙。', example_ko='사막에 들어서니 눈앞에 아득히 넓은 황사가 펼쳐졌다.' WHERE id=3444;",
"UPDATE words SET korean='막연하다', example_zh='听到这个消息，他感到一片茫然，不知所措。', example_ko='이 소식을 듣자 그는 막연하여 어찌할 바를 몰랐다.' WHERE id=3445;",
"UPDATE words SET korean='맹목적이다', example_zh='盲目跟风会带来很多问题。', example_ko='맹목적으로 유행을 따르면 많은 문제가 생긴다.' WHERE id=3446;",
"UPDATE words SET korean='위장하다', example_zh='他冒充医生，骗取了病人的信任。', example_ko='그는 의사를 위장하여 환자의 신뢰를 속였다.' WHERE id=3447;",
"UPDATE words SET korean='무성하다', example_zh='春天到了，花园里的植物长得茂盛。', example_ko='봄이 되자 정원의 식물들이 무성하게 자랐다.' WHERE id=3448;",
"UPDATE words SET korean='~개 (셈 단위)', example_zh='这枚邮票非常珍贵，是限量版的。', example_ko='이 우표는 매우 귀중한 한정판이다.' WHERE id=3449;",
"UPDATE words SET korean='방법이 없다', example_zh='他对这个问题没辙，不知道怎么解决。', example_ko='그는 이 문제에 방법이 없어 어떻게 해결해야 할지 모른다.' WHERE id=3450;",
"UPDATE words SET korean='매개체', example_zh='网络已成为信息传播的重要媒介。', example_ko='인터넷은 정보 전달의 중요한 매개체가 됐다.' WHERE id=3451;",
"UPDATE words SET korean='미디어', example_zh='媒体的报道影响了公众对事件的看法。', example_ko='미디어의 보도가 사건에 대한 대중의 시각에 영향을 미쳤다.' WHERE id=3452;",
"UPDATE words SET korean='아름답다', example_zh='这座公园的景色美观，吸引了很多游客。', example_ko='이 공원의 경치가 아름다워 많은 관광객을 끌어들인다.' WHERE id=3453;",
"UPDATE words SET korean='행복하다, 완벽하다', example_zh='他们过着美满幸福的生活。', example_ko='그들은 행복하고 완벽한 생활을 하고 있다.' WHERE id=3454;",
"UPDATE words SET korean='아름답다, 묘하다', example_zh='山间的景色美妙绝伦，令人心旷神怡。', example_ko='산간의 경치가 더없이 아름다워 마음이 탁 트이는 느낌이다.' WHERE id=3455;",
"UPDATE words SET korean='외래 진찰', example_zh='他每周去医院门诊复查一次。', example_ko='그는 매주 병원 외래 진찰을 받으러 간다.' WHERE id=3456;",
"UPDATE words SET korean='덮다, 속다', example_zh='他被对方的花言巧语蒙住了。', example_ko='그는 상대방의 감언이설에 속아 넘어갔다.' WHERE id=3457;",
"UPDATE words SET korean='싹트다', example_zh='春天来了，树枝上开始萌芽。', example_ko='봄이 오자 나뭇가지에 새싹이 돋기 시작했다.' WHERE id=3458;",
"UPDATE words SET korean='맹렬하다', example_zh='风雪猛烈，出行十分危险。', example_ko='눈보라가 맹렬하여 외출이 매우 위험하다.' WHERE id=3459;",
"UPDATE words SET korean='꿈, 꿈꾸다', example_zh='他从小就有一个梦想，要成为一名科学家。', example_ko='그는 어릴 때부터 과학자가 되겠다는 꿈이 있었다.' WHERE id=3460;",
]

with open('hsk6_data_2.sql', 'a', encoding='utf-8') as f:
    for line in lines:
        f.write(line + '\n')

print(f'Done, appended {len(lines)} lines')
