import io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

lines = [
    "UPDATE words SET meaning='브레이크를 걸다, 급정거하다', example_zh='司机紧急刹车，避免了一场事故。', example_ko='운전사가 급정거해서 사고를 피했다.' WHERE id=3774;",
    "UPDATE words SET meaning='뭐, 무엇', example_zh='你在找啥，我帮你找。', example_ko='무엇을 찾고 있어? 내가 도와줄게.' WHERE id=3775;",
    "UPDATE words SET meaning='선별하다, 스크리닝하다', example_zh='简历筛选后，只有十人进入面试。', example_ko='이력서 선별 후 10명만 면접에 진출했다.' WHERE id=3776;",
    "UPDATE words SET meaning='산맥', example_zh='喜马拉雅山脉是世界上最高的山脉。', example_ko='히말라야 산맥은 세계에서 가장 높은 산맥이다.' WHERE id=3777;",
    "UPDATE words SET meaning='반짝이다, 빛나다', example_zh='夜空中的星星闪烁着迷人的光芒。', example_ko='밤하늘의 별들이 매혹적인 빛을 반짝이고 있다.' WHERE id=3778;",
    "UPDATE words SET meaning='뛰어나다, 잘하다', example_zh='他擅长数学，每次考试都名列前茅。', example_ko='그는 수학을 잘해서 시험마다 항상 상위권이다.' WHERE id=3779;",
    "UPDATE words SET meaning='제멋대로 하다, 독단으로 하다', example_zh='他擅自做了决定，没有征求大家意见。', example_ko='그는 모두의 의견을 구하지 않고 제멋대로 결정을 내렸다.' WHERE id=3780;",
    "UPDATE words SET meaning='상표', example_zh='这个商标已经在全球注册。', example_ko='이 상표는 이미 전 세계에 등록되었다.' WHERE id=3781;",
    "UPDATE words SET meaning='골치 아프다', example_zh='这件事让他很伤脑筋，不知如何处理。', example_ko='이 일이 그를 골치 아프게 해서 어떻게 처리해야 할지 모르겠다.' WHERE id=3782;",
    "UPDATE words SET meaning='상급, 상사', example_zh='他按照上级的指示完成了任务。', example_ko='그는 상급의 지시에 따라 임무를 완수했다.' WHERE id=3783;",
    "UPDATE words SET meaning='향상심, 발전 의지', example_zh='有上进心的人更容易取得成功。', example_ko='향상심이 있는 사람이 더 쉽게 성공한다.' WHERE id=3784;",
    "UPDATE words SET meaning='부임하다, 취임하다', example_zh='新市长明天正式上任。', example_ko='새 시장이 내일 공식적으로 부임한다.' WHERE id=3785;",
    "UPDATE words SET meaning='중독되다', example_zh='他对手机游戏上瘾了，每天玩好几个小时。', example_ko='그는 모바일 게임에 중독되어 매일 몇 시간씩 한다.' WHERE id=3786;",
    "UPDATE words SET meaning='상류', example_zh='洪水发生在河流的上游地区。', example_ko='홍수가 강 상류 지역에서 발생했다.' WHERE id=3787;",
    "UPDATE words SET meaning='전하다, 가져다 주다', example_zh='请你捎个口信给他。', example_ko='그에게 말을 전해 주세요.' WHERE id=3788;",
    "UPDATE words SET meaning='나뭇가지 끝', example_zh='鸟儿站在树梢上歌唱。', example_ko='새가 나뭇가지 끝에 앉아 노래한다.' WHERE id=3789;",
    "UPDATE words SET meaning='보초, 경계', example_zh='士兵在门口站哨。', example_ko='병사가 문 앞에서 보초를 서고 있다.' WHERE id=3790;",
    "UPDATE words SET meaning='사치하다', example_zh='他的生活方式非常奢侈，花费巨大。', example_ko='그의 생활 방식은 매우 사치스러워 지출이 엄청나다.' WHERE id=3791;",
    "UPDATE words SET meaning='설립하다', example_zh='政府设立了专项基金帮助贫困学生。', example_ko='정부가 빈곤 학생을 돕는 전용 기금을 설립했다.' WHERE id=3792;",
    "UPDATE words SET meaning='구상하다, 상정하다', example_zh='我们设想了多种可能的解决方案。', example_ko='우리는 여러 가능한 해결 방안을 구상했다.' WHERE id=3793;",
    "UPDATE words SET meaning='설치하다, 배치하다', example_zh='公司在各部门设置了监控摄像头。', example_ko='회사는 각 부서에 감시 카메라를 설치했다.' WHERE id=3794;",
    "UPDATE words SET meaning='커뮤니티, 지역 사회', example_zh='这个社区的居民互相帮助，关系融洽。', example_ko='이 커뮤니티의 주민들은 서로 돕고 사이가 좋다.' WHERE id=3795;",
    "UPDATE words SET meaning='관련되다, 연관되다', example_zh='这项决策涉及到公司的未来发展。', example_ko='이 결정은 회사의 미래 발전과 관련된다.' WHERE id=3796;",
    "UPDATE words SET meaning='섭취하다', example_zh='每天要适量摄取蛋白质和维生素。', example_ko='매일 적정량의 단백질과 비타민을 섭취해야 한다.' WHERE id=3797;",
    "UPDATE words SET meaning='섭씨', example_zh='今天的气温是三十五摄氏度。', example_ko='오늘 기온은 35도다.' WHERE id=3798;",
    "UPDATE words SET meaning='심오하다', example_zh='这位哲学家的思想深奥难懂。', example_ko='이 철학자의 사상은 심오해서 이해하기 어렵다.' WHERE id=3799;",
    "UPDATE words SET meaning='깊다, 침착하다', example_zh='他说话的声音深沉而有力。', example_ko='그의 말소리는 깊고 힘차다.' WHERE id=3800;",
    "UPDATE words SET meaning='깊은 정과 두터운 우의', example_zh='多年的合作让两人建立了深情厚谊。', example_ko='수년간의 협력으로 두 사람 사이에 깊은 정과 두터운 우의가 쌓였다.' WHERE id=3801;",
    "UPDATE words SET meaning='신고하다, 보고하다', example_zh='回国后需要向海关申报所购物品。', example_ko='귀국 후 세관에 구입한 물품을 신고해야 한다.' WHERE id=3802;",
    "UPDATE words SET meaning='신사', example_zh='他举止优雅，是一位真正的绅士。', example_ko='그는 행동이 우아해서 진정한 신사다.' WHERE id=3803;",
    "UPDATE words SET meaning='신음하다', example_zh='伤者在病床上痛苦地呻吟。', example_ko='부상자가 병상에서 고통스럽게 신음하고 있다.' WHERE id=3804;",
    "UPDATE words SET meaning='신기하다, 기묘하다', example_zh='这种植物具有神奇的药用价值。', example_ko='이 식물은 신기한 약용 가치를 가지고 있다.' WHERE id=3805;",
    "UPDATE words SET meaning='위풍당당하다', example_zh='他穿上制服后，看起来格外神气。', example_ko='그가 제복을 입으니 한층 위풍당당해 보인다.' WHERE id=3806;",
    "UPDATE words SET meaning='표정, 안색', example_zh='从他的神情可以看出他很紧张。', example_ko='그의 표정을 보면 그가 매우 긴장하고 있음을 알 수 있다.' WHERE id=3807;",
    "UPDATE words SET meaning='안색, 기색', example_zh='她的神色有些不安，似乎有什么心事。', example_ko='그녀의 안색이 좀 불안해 보여서 무언가 고민이 있는 것 같다.' WHERE id=3808;",
    "UPDATE words SET meaning='신성하다', example_zh='保护自然环境是一项神圣的使命。', example_ko='자연환경을 보호하는 것은 신성한 사명이다.' WHERE id=3809;",
    "UPDATE words SET meaning='모습, 태도', example_zh='他的神态表明他对这个问题很感兴趣。', example_ko='그의 모습을 보면 이 문제에 매우 관심이 있음을 알 수 있다.' WHERE id=3810;",
    "UPDATE words SET meaning='신선, 신령', example_zh='故事里的神仙能飞天遁地。', example_ko='이야기 속의 신선은 하늘을 날고 땅 속으로 사라질 수 있다.' WHERE id=3811;",
    "UPDATE words SET meaning='심사하다, 검토하다', example_zh='委员会对申请材料进行了严格审查。', example_ko='위원회가 신청 자료에 대해 엄격한 심사를 진행했다.' WHERE id=3812;",
    "UPDATE words SET meaning='심리하다, 재심하다', example_zh='法院将于下周审理这起案件。', example_ko='법원이 다음 주에 이 사건을 심리할 예정이다.' WHERE id=3813;",
    "UPDATE words SET meaning='심미하다, 미를 감상하다', example_zh='她有很高的审美水平。', example_ko='그녀는 매우 높은 심미 수준을 가지고 있다.' WHERE id=3814;",
    "UPDATE words SET meaning='심판하다', example_zh='历史将会审判那些犯下罪行的人。', example_ko='역사가 죄를 저지른 사람들을 심판할 것이다.' WHERE id=3815;",
    "UPDATE words SET meaning='침투하다, 스며들다', example_zh='雨水渗透到了地下，补充了地下水资源。', example_ko='빗물이 지하로 침투해서 지하수 자원을 보충했다.' WHERE id=3816;",
    "UPDATE words SET meaning='신중하다', example_zh='做重要决定时要慎重考虑。', example_ko='중요한 결정을 내릴 때는 신중하게 생각해야 한다.' WHERE id=3817;",
    "UPDATE words SET meaning='생존하다', example_zh='在极端条件下，只有最强壮的才能生存。', example_ko='극단적인 환경에서는 가장 강한 자만이 생존할 수 있다.' WHERE id=3818;",
    "UPDATE words SET meaning='생기, 활력', example_zh='春天来了，大地充满了生机。', example_ko='봄이 오자 대지가 생기로 가득찼다.' WHERE id=3819;",
    "UPDATE words SET meaning='생리', example_zh='了解生理知识有助于维护身体健康。', example_ko='생리 지식을 알면 신체 건강을 유지하는 데 도움이 된다.' WHERE id=3820;",
    "UPDATE words SET meaning='낯설다, 생소하다', example_zh='他刚来到这里，对周围的环境还很生疏。', example_ko='그는 막 이곳에 와서 주변 환경이 아직 낯설다.' WHERE id=3821;",
    "UPDATE words SET meaning='생태', example_zh='保护生态环境是可持续发展的基础。', example_ko='생태 환경을 보호하는 것이 지속가능한 발전의 기초다.' WHERE id=3822;",
    "UPDATE words SET meaning='생물', example_zh='地球上有数百万种生物。', example_ko='지구상에는 수백만 종의 생물이 있다.' WHERE id=3823;",
    "UPDATE words SET meaning='효력이 발생하다', example_zh='新法律将于明年一月一日生效。', example_ko='새 법률은 내년 1월 1일에 효력이 발생한다.' WHERE id=3824;",
    "UPDATE words SET meaning='녹슬다', example_zh='长时间不使用的工具容易生锈。', example_ko='오랫동안 사용하지 않은 도구는 녹슬기 쉽다.' WHERE id=3825;",
    "UPDATE words SET meaning='낳다, 출산하다', example_zh='她明年打算生育第二个孩子。', example_ko='그녀는 내년에 둘째 아이를 낳을 계획이다.' WHERE id=3826;",
    "UPDATE words SET meaning='가축', example_zh='农民精心照料牲畜。', example_ko='농부가 가축을 정성껏 돌본다.' WHERE id=3827;",
    "UPDATE words SET meaning='성명하다, 발표하다', example_zh='公司发表声明，否认了相关指控。', example_ko='회사는 성명을 발표해 관련 혐의를 부인했다.' WHERE id=3828;",
    "UPDATE words SET meaning='기세, 위세', example_zh='这次演讲声势浩大，吸引了众多听众。', example_ko='이번 연설은 기세가 당당해서 많은 청중을 끌어들였다.' WHERE id=3829;",
    "UPDATE words SET meaning='명예, 명성', example_zh='他为公司赢得了良好的声誉。', example_ko='그는 회사를 위해 좋은 명성을 얻었다.' WHERE id=3830;",
    "UPDATE words SET meaning='성도, 주도', example_zh='成都是四川省的省会城市。', example_ko='청두는 쓰촨성의 성도다.' WHERE id=3831;",
    "UPDATE words SET meaning='많이 나다, 풍부하게 생산되다', example_zh='这个地区盛产各种热带水果。', example_ko='이 지역은 각종 열대 과일이 풍부하게 생산된다.' WHERE id=3832;",
    "UPDATE words SET meaning='활짝 피다', example_zh='春天桃花盛开，美不胜收。', example_ko='봄에 복숭아꽃이 활짝 피어 아름답기 그지없다.' WHERE id=3833;",
    "UPDATE words SET meaning='후한 대접, 진심 어린 환대', example_zh='主人以盛情款待了来访的客人。', example_ko='주인은 진심 어린 환대로 방문한 손님을 대접했다.' WHERE id=3834;",
    "UPDATE words SET meaning='성행하다, 유행하다', example_zh='这种风气在年轻人中盛行。', example_ko='이런 풍조가 젊은이들 사이에서 유행하고 있다.' WHERE id=3835;",
    "UPDATE words SET meaning='승부, 이기고 지기', example_zh='比赛的胜负取决于双方的实力。', example_ko='경기의 승부는 양측의 실력에 달려 있다.' WHERE id=3836;",
    "UPDATE words SET meaning='실수', example_zh='他因一时失误，导致了重大损失。', example_ko='그는 일시적인 실수로 큰 손실을 초래했다.' WHERE id=3837;",
    "UPDATE words SET meaning='실종되다', example_zh='那名男孩已经失踪三天了。', example_ko='그 남자아이는 이미 3일째 실종되어 있다.' WHERE id=3838;",
    "UPDATE words SET meaning='사범, 모범이 되다', example_zh='她毕业于师范大学，成为了一名教师。', example_ko='그녀는 사범대학을 졸업해 교사가 되었다.' WHERE id=3839;",
    "UPDATE words SET meaning='가하다, 시행하다', example_zh='他对对手施加了巨大压力。', example_ko='그는 상대방에게 큰 압력을 가했다.' WHERE id=3840;",
    "UPDATE words SET meaning='펼치다, 발휘하다', example_zh='她终于有机会施展自己的才华。', example_ko='그녀는 마침내 자신의 재능을 펼칠 기회가 생겼다.' WHERE id=3841;",
    "UPDATE words SET meaning='시체', example_zh='警察在现场发现了一具尸体。', example_ko='경찰이 현장에서 시체 한 구를 발견했다.' WHERE id=3842;",
    "UPDATE words SET meaning='줍다, 집다', example_zh='他在路上拾到了一个钱包。', example_ko='그는 길에서 지갑을 주웠다.' WHERE id=3843;",
    "UPDATE words SET meaning='충분하다, 완전하다', example_zh='他是一个十足的完美主义者。', example_ko='그는 완전한 완벽주의자다.' WHERE id=3844;",
    "UPDATE words SET meaning='식별하다', example_zh='这种系统能识别人脸。', example_ko='이 시스템은 얼굴을 식별할 수 있다.' WHERE id=3845;",
    "UPDATE words SET meaning='시차', example_zh='跨国旅行经常会有时差问题。', example_ko='국제 여행을 하면 자주 시차 문제가 생긴다.' WHERE id=3846;",
    "UPDATE words SET meaning='때때로, 자주', example_zh='他时常想起家乡的味道。', example_ko='그는 때때로 고향의 맛을 떠올린다.' WHERE id=3847;",
    "UPDATE words SET meaning='때로는', example_zh='他时而开心，时而忧愁，心情起伏不定。', example_ko='그는 때로는 기쁘고 때로는 슬퍼서 감정 기복이 있다.' WHERE id=3848;",
    "UPDATE words SET meaning='세월, 시간', example_zh='美好的时光总是过得很快。', example_ko='아름다운 시간은 항상 빠르게 지나간다.' WHERE id=3849;",
    "UPDATE words SET meaning='시기, 기회', example_zh='他抓住了市场变化的时机，取得了成功。', example_ko='그는 시장 변화의 시기를 잡아 성공을 거뒀다.' WHERE id=3850;",
    "UPDATE words SET meaning='시사, 시사 문제', example_zh='他经常关注国内外的时事动态。', example_ko='그는 국내외 시사 동향을 자주 관심 있게 살핀다.' WHERE id=3851;",
    "UPDATE words SET meaning='패션, 유행 옷', example_zh='她喜欢参加各种时装展览。', example_ko='그녀는 각종 패션쇼에 참가하는 것을 좋아한다.' WHERE id=3852;",
    "UPDATE words SET meaning='실리, 실속', example_zh='这个方案既经济又实惠，很受欢迎。', example_ko='이 방안은 경제적이고 실속 있어서 인기가 많다.' WHERE id=3853;",
    "UPDATE words SET meaning='실력', example_zh='他凭借扎实的实力赢得了比赛。', example_ko='그는 탄탄한 실력으로 대회에서 우승했다.' WHERE id=3854;",
    "UPDATE words SET meaning='실시하다', example_zh='政府将于明年实施新的教育政策。', example_ko='정부는 내년에 새 교육 정책을 실시할 예정이다.' WHERE id=3855;",
    "UPDATE words SET meaning='사실에서 출발하다', example_zh='做研究要实事求是，不能凭空想象。', example_ko='연구를 할 때는 사실에서 출발해야 하며 공상에 근거해서는 안 된다.' WHERE id=3856;",
    "UPDATE words SET meaning='본질, 실질', example_zh='我们要看清问题的实质，不被表象所迷惑。', example_ko='우리는 문제의 본질을 파악해야 하며 겉모습에 속아서는 안 된다.' WHERE id=3857;",
    "UPDATE words SET meaning='석유', example_zh='石油是重要的化石能源之一。', example_ko='석유는 중요한 화석 에너지 중 하나다.' WHERE id=3858;",
    "UPDATE words SET meaning='사명', example_zh='教育是每位教师的神圣使命。', example_ko='교육은 모든 교사의 신성한 사명이다.' WHERE id=3859;",
    "UPDATE words SET meaning='옳고 그름', example_zh='他能清楚地分辨是非对错。', example_ko='그는 옳고 그름을 명확하게 구별할 수 있다.' WHERE id=3860;",
    "UPDATE words SET meaning='시도하다', example_zh='他试图说服对方，但没有成功。', example_ko='그는 상대방을 설득하려 했지만 성공하지 못했다.' WHERE id=3861;",
    "UPDATE words SET meaning='시험하다, 실험하다', example_zh='新药在上市前需要经过严格的试验。', example_ko='신약은 출시 전에 엄격한 실험을 거쳐야 한다.' WHERE id=3862;",
    "UPDATE words SET meaning='반드시 ~할 것이다', example_zh='这种趋势势必影响未来的发展。', example_ko='이런 추세는 반드시 미래 발전에 영향을 미칠 것이다.' WHERE id=3863;",
    "UPDATE words SET meaning='세력', example_zh='这股势力在当地具有很大的影响力。', example_ko='이 세력은 현지에서 매우 큰 영향력을 가지고 있다.' WHERE id=3864;",
    "UPDATE words SET meaning='대대, 세대', example_zh='这个家族世代居住在这个村子里。', example_ko='이 가문은 대대로 이 마을에 거주하고 있다.' WHERE id=3865;",
    "UPDATE words SET meaning='세계관', example_zh='不同的文化背景会影响人的世界观。', example_ko='다양한 문화적 배경이 사람의 세계관에 영향을 미친다.' WHERE id=3866;",
    "UPDATE words SET meaning='시범을 보이다', example_zh='老师向学生示范了正确的操作方法。', example_ko='선생님이 학생들에게 올바른 조작 방법을 시범 보였다.' WHERE id=3867;",
    "UPDATE words SET meaning='시위하다', example_zh='学生们走上街头示威，表达他们的诉求。', example_ko='학생들이 거리로 나가 시위하며 자신들의 요구를 표현했다.' WHERE id=3868;",
    "UPDATE words SET meaning='암시하다, 신호를 보내다', example_zh='他用眼神示意我保持安静。', example_ko='그는 눈빛으로 내게 조용히 하라고 신호를 보냈다.' WHERE id=3869;",
    "UPDATE words SET meaning='석방하다', example_zh='警察将嫌疑人释放了。', example_ko='경찰이 용의자를 석방했다.' WHERE id=3870;",
    "UPDATE words SET meaning='사고', example_zh='这场交通事故造成了人员伤亡。', example_ko='이 교통사고로 인명 피해가 발생했다.' WHERE id=3871;",
    "UPDATE words SET meaning='사적, 업적', example_zh='英雄的事迹激励了一代又一代人。', example_ko='영웅의 업적이 세대를 이어 사람들을 격려했다.' WHERE id=3872;",
    "UPDATE words SET meaning='사건', example_zh='这起事件引发了广泛的社会关注。', example_ko='이 사건이 광범위한 사회적 관심을 불러일으켰다.' WHERE id=3873;",
    "UPDATE words SET meaning='사태, 형세', example_zh='事态发展越来越严峻，需要立即采取行动。', example_ko='사태 발전이 점점 심각해져서 즉각 행동을 취해야 한다.' WHERE id=3874;",
    "UPDATE words SET meaning='사무, 업무', example_zh='他处理公司的日常事务。', example_ko='그는 회사의 일상적인 업무를 처리한다.' WHERE id=3875;",
    "UPDATE words SET meaning='사항', example_zh='请注意以下几项重要事项。', example_ko='다음 몇 가지 중요한 사항에 주의해 주세요.' WHERE id=3876;",
    "UPDATE words SET meaning='사업, 커리어', example_zh='他的事业发展得非常顺利。', example_ko='그의 사업은 매우 순조롭게 발전하고 있다.' WHERE id=3877;",
    "UPDATE words SET meaning='적합하다, 알맞다', example_zh='这个地方气候适宜，适合居住。', example_ko='이곳은 기후가 적합해서 거주하기에 알맞다.' WHERE id=3878;",
    "UPDATE words SET meaning='시력', example_zh='长时间看手机会损害视力。', example_ko='오랫동안 핸드폰을 보면 시력이 손상된다.' WHERE id=3879;",
    "UPDATE words SET meaning='시선', example_zh='她的视线停留在那张照片上。', example_ko='그녀의 시선이 그 사진에 멈추었다.' WHERE id=3880;",
    "UPDATE words SET meaning='시야', example_zh='站在山顶，视野非常开阔。', example_ko='산꼭대기에 서면 시야가 매우 넓다.' WHERE id=3881;",
    "UPDATE words SET meaning='별세하다, 세상을 뜨다', example_zh='这位著名作家昨天逝世，享年八十岁。', example_ko='이 유명 작가가 어제 향년 80세로 별세했다.' WHERE id=3882;",
    "UPDATE words SET meaning='소장하다, 수집하다', example_zh='他收藏了许多珍贵的古董。', example_ko='그는 많은 귀한 골동품을 소장하고 있다.' WHERE id=3883;",
    "UPDATE words SET meaning='수축하다', example_zh='金属遇冷会收缩。', example_ko='금속은 냉각되면 수축한다.' WHERE id=3884;",
    "UPDATE words SET meaning='수익, 이익', example_zh='这项投资带来了可观的收益。', example_ko='이 투자는 상당한 수익을 가져다 주었다.' WHERE id=3885;",
    "UPDATE words SET meaning='라디오', example_zh='他习惯在早上听收音机新闻。', example_ko='그는 아침에 라디오 뉴스를 듣는 습관이 있다.' WHERE id=3886;",
    "UPDATE words SET meaning='수법, 기교', example_zh='这位画家的手法独特，令人印象深刻。', example_ko='이 화가의 수법은 독특해서 인상적이다.' WHERE id=3887;",
    "UPDATE words SET meaning='손짓', example_zh='他用手势示意大家安静。', example_ko='그는 손짓으로 모두에게 조용히 하라고 암시했다.' WHERE id=3888;",
    "UPDATE words SET meaning='손재주, 기술', example_zh='这位工匠有一手精湛的手艺。', example_ko='이 장인은 정교한 손재주를 가지고 있다.' WHERE id=3889;",
    "UPDATE words SET meaning='가장 중요한', example_zh='安全是工作中的首要任务。', example_ko='안전은 업무에서 가장 중요한 임무다.' WHERE id=3890;",
    "UPDATE words SET meaning='수호하다, 지키다', example_zh='士兵守护着国家的边境安全。', example_ko='병사들이 국가의 국경 안전을 수호하고 있다.' WHERE id=3891;",
    "UPDATE words SET meaning='고생하다, 시달리다', example_zh='他在狱中受尽了苦楚，备受煎熬。', example_ko='그는 감옥에서 온갖 고생을 다하며 시달렸다.' WHERE id=3892;",
    "UPDATE words SET meaning='수여하다, 주다', example_zh='大学授予他荣誉博士学位。', example_ko='대학교가 그에게 명예 박사 학위를 수여했다.' WHERE id=3893;",
    "UPDATE words SET meaning='서예', example_zh='他从小学习书法，写得一手好字。', example_ko='그는 어릴 때부터 서예를 배워서 글씨를 잘 쓴다.' WHERE id=3894;",
    "UPDATE words SET meaning='서적, 책', example_zh='图书馆里有数万册书籍供读者借阅。', example_ko='도서관에는 독자들이 빌릴 수 있는 수만 권의 서적이 있다.' WHERE id=3895;",
    "UPDATE words SET meaning='서기, 비서', example_zh='他被选为公司的书记，负责记录会议内容。', example_ko='그는 회사의 서기로 선출되어 회의 내용을 기록한다.' WHERE id=3896;",
    "UPDATE words SET meaning='서면, 문서', example_zh='请将申请以书面形式提交。', example_ko='신청서를 서면 형식으로 제출해 주세요.' WHERE id=3897;",
    "UPDATE words SET meaning='유쾌하다, 상쾌하다', example_zh='放假后，他感到心情格外舒畅。', example_ko='휴가 후 그는 기분이 한결 유쾌하다고 느꼈다.' WHERE id=3898;",
    "UPDATE words SET meaning='소홀히 하다, 부주의하다', example_zh='他因为疏忽大意，犯下了严重错误。', example_ko='그는 부주의로 심각한 실수를 저질렀다.' WHERE id=3899;",
    "UPDATE words SET meaning='~에 속하다', example_zh='这种植物数热带物种。', example_ko='이 식물은 열대 종에 속한다.' WHERE id=3900;",
    "UPDATE words SET meaning='세우다, 수직으로 놓다', example_zh='他竖起大拇指，表示称赞。', example_ko='그는 엄지손가락을 세워서 칭찬을 표시했다.' WHERE id=3901;",
    "UPDATE words SET meaning='묶음, 단발', example_zh='他手持一束鲜花，等待着她。', example_ko='그는 꽃다발을 들고 그녀를 기다리고 있었다.' WHERE id=3902;",
    "UPDATE words SET meaning='속박하다, 얽매다', example_zh='传统观念束缚了她的思想。', example_ko='전통 관념이 그녀의 생각을 속박했다.' WHERE id=3903;",
    "UPDATE words SET meaning='세우다, 수립하다', example_zh='他在业界树立了良好的形象。', example_ko='그는 업계에서 좋은 이미지를 수립했다.' WHERE id=3904;",
    "UPDATE words SET meaning='수량, 액수', example_zh='这次捐款的数额超过了预期。', example_ko='이번 기부금의 수액이 예상을 초과했다.' WHERE id=3905;",
    "UPDATE words SET meaning='수량, 숫자', example_zh='这批货物的数目有些不对。', example_ko='이 물건들의 수량이 약간 맞지 않는다.' WHERE id=3906;",
    "UPDATE words SET meaning='장난치다, 놀다', example_zh='他喜欢在朋友面前耍花招。', example_ko='그는 친구들 앞에서 장난을 치는 것을 좋아한다.' WHERE id=3907;",
    "UPDATE words SET meaning='늙다, 노쇠하다', example_zh='人体随着年龄的增长会逐渐衰老。', example_ko='인체는 나이가 들수록 점점 노쇠해진다.' WHERE id=3908;",
    "UPDATE words SET meaning='쇠퇴하다', example_zh='经济衰退导致失业率上升。', example_ko='경제 쇠퇴로 실업률이 상승했다.' WHERE id=3909;",
    "UPDATE words SET meaning='이끌다, 인솔하다', example_zh='将军率领军队打败了敌人。', example_ko='장군이 군대를 이끌고 적을 물리쳤다.' WHERE id=3910;",
    "UPDATE words SET meaning='(涮锅子) 샤브샤브', example_zh='冬天吃涮锅子最暖和了。', example_ko='겨울에 샤브샤브를 먹으면 가장 따뜻하다.' WHERE id=3911;",
    "UPDATE words SET meaning='쌍둥이', example_zh='她生了一对双胞胎，非常高兴。', example_ko='그녀는 쌍둥이를 낳아 매우 기뻤다.' WHERE id=3912;",
    "UPDATE words SET meaning='시원하다, 쾌활하다', example_zh='他做事爽快，从不拖拉。', example_ko='그는 일을 시원하게 처리해서 절대 미적거리지 않는다.' WHERE id=3913;",
    "UPDATE words SET meaning='수리', example_zh='兴修水利是农业发展的重要保障。', example_ko='수리 시설을 건설하는 것이 농업 발전의 중요한 보장이다.' WHERE id=3914;",
    "UPDATE words SET meaning='수도꼭지', example_zh='水龙头坏了，需要维修。', example_ko='수도꼭지가 고장나서 수리가 필요하다.' WHERE id=3915;",
    "UPDATE words SET meaning='시멘트', example_zh='建筑工人用水泥砌墙。', example_ko='건축 노동자들이 시멘트로 벽을 쌓았다.' WHERE id=3916;",
    "UPDATE words SET meaning='사법', example_zh='司法公正是法治社会的基础。', example_ko='사법 공정성은 법치 사회의 기초다.' WHERE id=3917;",
    "UPDATE words SET meaning='사령관', example_zh='司令发出了命令，部队立即行动。', example_ko='사령관이 명령을 내리자 부대가 즉각 행동했다.' WHERE id=3918;",
    "UPDATE words SET meaning='그리워하다, 그리다', example_zh='他在异乡思念着远方的家人。', example_ko='그는 타향에서 먼 곳의 가족을 그리워했다.' WHERE id=3919;",
    "UPDATE words SET meaning='생각하다, 탐색하다', example_zh='他思索着如何解决这个难题。', example_ko='그는 이 어려운 문제를 어떻게 해결할지 생각하고 있다.' WHERE id=3920;",
    "UPDATE words SET meaning='사유, 사고력', example_zh='创造性思维是推动社会进步的重要力量。', example_ko='창의적 사고력은 사회 발전을 이끄는 중요한 힘이다.' WHERE id=3921;",
    "UPDATE words SET meaning='생각의 실마리, 사유', example_zh='他的思绪飘向了遥远的童年时代。', example_ko='그의 생각은 아득한 어린 시절로 흘러갔다.' WHERE id=3922;",
    "UPDATE words SET meaning='제멋대로, 몰래', example_zh='他私自做了决定，没有告诉任何人。', example_ko='그는 아무에게도 말하지 않고 제멋대로 결정을 내렸다.' WHERE id=3923;",
    "UPDATE words SET meaning='점잖다, 우아하다', example_zh='他的举止非常斯文，给人留下了好印象。', example_ko='그의 행동이 매우 우아해서 좋은 인상을 남겼다.' WHERE id=3924;",
    "UPDATE words SET meaning='사망', example_zh='他的死亡让所有人都感到震惊。', example_ko='그의 사망은 모든 사람을 충격에 빠뜨렸다.' WHERE id=3925;",
    "UPDATE words SET meaning='사지, 팔다리', example_zh='运动员的四肢非常有力。', example_ko='운동선수의 팔다리는 매우 힘이 세다.' WHERE id=3926;",
    "UPDATE words SET meaning='거리낌 없이 제멋대로 하다', example_zh='他肆无忌惮地破坏了公共设施。', example_ko='그는 거리낌 없이 공공 시설을 파괴했다.' WHERE id=3927;",
    "UPDATE words SET meaning='사육하다, 기르다', example_zh='他家里饲养了一只小猫。', example_ko='그의 집에서 새끼 고양이 한 마리를 기르고 있다.' WHERE id=3928;",
    "UPDATE words SET meaning='솟아오르다, 으쓱하다', example_zh='高山耸立于平原之上。', example_ko='높은 산이 평원 위에 솟아오르고 있다.' WHERE id=3929;",
    "UPDATE words SET meaning='(배를 세는 단위) 척', example_zh='港口里停泊着数艘大型货轮。', example_ko='항구에 대형 화물선 몇 척이 정박해 있다.' WHERE id=3930;",
    "UPDATE words SET meaning='검색하다', example_zh='他在网上搜索相关资料。', example_ko='그는 인터넷에서 관련 자료를 검색했다.' WHERE id=3931;",
    "UPDATE words SET meaning='소생하다, 깨어나다', example_zh='经过抢救，病人终于苏醒了。', example_ko='응급처치 끝에 환자가 마침내 소생했다.' WHERE id=3932;",
    "UPDATE words SET meaning='속담, 격언', example_zh='俗话说，天下没有免费的午餐。', example_ko='속담에 이르기를, 세상에 공짜 점심은 없다고 했다.' WHERE id=3933;",
    "UPDATE words SET meaning='형상화하다, 조형하다', example_zh='这位作家善于塑造复杂的人物形象。', example_ko='이 작가는 복잡한 인물을 형상화하는 것을 잘한다.' WHERE id=3934;",
    "UPDATE words SET meaning='채식', example_zh='她因健康原因改为素食。', example_ko='그녀는 건강상의 이유로 채식으로 바꿨다.' WHERE id=3935;",
    "UPDATE words SET meaning='소질, 자질', example_zh='每个人都应该不断提高自己的素质。', example_ko='모든 사람은 끊임없이 자신의 자질을 향상시켜야 한다.' WHERE id=3936;",
    "UPDATE words SET meaning='소송하다', example_zh='他决定通过诉讼途径维护自己的权益。', example_ko='그는 소송 방법으로 자신의 권익을 지키기로 결정했다.' WHERE id=3937;",
    "UPDATE words SET meaning='그만하다, 포기하다', example_zh='算了，这件事我不想再追究了。', example_ko='그만하자, 이 일은 더 이상 따지고 싶지 않다.' WHERE id=3938;",
    "UPDATE words SET meaning='셈, 계산하다', example_zh='这道算数题对小学生来说有点难。', example_ko='이 산수 문제는 초등학생에게는 약간 어렵다.' WHERE id=3939;",
    "UPDATE words SET meaning='즉시, 곧바로', example_zh='他随即离开了现场。', example_ko='그는 즉시 현장을 떠났다.' WHERE id=3940;",
    "UPDATE words SET meaning='몸에 지니고', example_zh='他随身携带了必要的证件。', example_ko='그는 필요한 증서를 몸에 지니고 다녔다.' WHERE id=3941;",
    "UPDATE words SET meaning='손에 잡히는 대로', example_zh='他随手关了灯，离开了房间。', example_ko='그는 손에 잡히는 대로 불을 끄고 방을 나갔다.' WHERE id=3942;",
    "UPDATE words SET meaning='마음대로, 제멋대로', example_zh='他随意丢弃垃圾，遭到了批评。', example_ko='그는 쓰레기를 마음대로 버려서 비판을 받았다.' WHERE id=3943;",
    "UPDATE words SET meaning='세월', example_zh='岁月如流水，转眼就是十年。', example_ko='세월은 흐르는 물 같아서 눈 깜짝할 사이에 10년이 지났다.' WHERE id=3944;",
    "UPDATE words SET meaning='터널', example_zh='工人们花了五年时间挖通了这条隧道。', example_ko='노동자들이 5년 동안 이 터널을 뚫었다.' WHERE id=3945;",
    "UPDATE words SET meaning='손상하다, 고장내다', example_zh='洪水损坏了大量农作物。', example_ko='홍수가 많은 농작물을 손상시켰다.' WHERE id=3946;",
    "UPDATE words SET meaning='배상을 청구하다', example_zh='受害者向肇事方索赔了一百万元。', example_ko='피해자가 가해자 측에 100만 위안의 배상을 청구했다.' WHERE id=3947;",
    "UPDATE words SET meaning='차라리, 아예', example_zh='反正都要淋雨，索性不带雨伞了。', example_ko='어차피 비를 맞을 거니, 아예 우산을 가져가지 않겠다.' WHERE id=3948;",
    "UPDATE words SET meaning='무너지다, 주저앉다', example_zh='地震使建筑物塌陷，造成严重损失。', example_ko='지진으로 건물이 무너져 심각한 피해가 발생했다.' WHERE id=3949;",
    "UPDATE words SET meaning='착실하다, 마음이 놓이다', example_zh='做完这件事后，他的心情踏实多了。', example_ko='이 일을 마친 후 그의 마음이 훨씬 착실해졌다.' WHERE id=3950;",
    "UPDATE words SET meaning='태풍', example_zh='台风带来了强风和暴雨。', example_ko='태풍이 강한 바람과 폭우를 몰고 왔다.' WHERE id=3951;",
    "UPDATE words SET meaning='우주 공간', example_zh='宇航员在太空中进行了科学实验。', example_ko='우주비행사가 우주 공간에서 과학 실험을 수행했다.' WHERE id=3952;",
    "UPDATE words SET meaning='태두, 권위자', example_zh='他是医学界的泰斗，受人尊敬。', example_ko='그는 의학계의 권위자로 존경받는다.' WHERE id=3953;",
    "UPDATE words SET meaning='마비되다', example_zh='大雪导致城市交通瘫痪。', example_ko='폭설로 도시 교통이 마비되었다.' WHERE id=3954;",
    "UPDATE words SET meaning='탐욕스럽다', example_zh='贪婪的行为最终会导致失败。', example_ko='탐욕스러운 행동은 결국 실패로 이어진다.' WHERE id=3955;",
    "UPDATE words SET meaning='탐오하다, 부패하다', example_zh='那名官员因贪污被逮捕。', example_ko='그 관리는 탐오로 체포되었다.' WHERE id=3956;",
    "UPDATE words SET meaning='노점', example_zh='街边有很多卖小吃的摊儿。', example_ko='거리에 간식을 파는 노점이 많다.' WHERE id=3957;",
    "UPDATE words SET meaning='탄성', example_zh='弹性材料在受力后能恢复原形。', example_ko='탄성 재료는 힘을 받은 후 원래 모양으로 돌아올 수 있다.' WHERE id=3958;",
    "UPDATE words SET meaning='솔직하다, 고백하다', example_zh='他坦白地说出了自己的错误。', example_ko='그는 솔직하게 자신의 실수를 털어놓았다.' WHERE id=3959;",
    "UPDATE words SET meaning='탐지하다, 측량하다', example_zh='科学家使用卫星探测了地球表面。', example_ko='과학자들이 위성을 이용해 지구 표면을 탐지했다.' WHERE id=3960;",
    "UPDATE words SET meaning='탐색하다', example_zh='人类一直在探索宇宙的奥秘。', example_ko='인류는 줄곧 우주의 비밀을 탐색하고 있다.' WHERE id=3961;",
    "UPDATE words SET meaning='토론하다, 탐구하다', example_zh='我们需要进一步探讨这个问题。', example_ko='우리는 이 문제에 대해 더욱 탐구해야 한다.' WHERE id=3962;",
    "UPDATE words SET meaning='방문하다, 살펴보다', example_zh='他去医院探望了生病的老友。', example_ko='그는 병원에 병든 오랜 친구를 방문했다.' WHERE id=3963;",
    "UPDATE words SET meaning='한숨 쉬다', example_zh='她叹气说，这件事真的很难解决。', example_ko='그녀는 한숨을 쉬며 이 일은 정말 해결하기 어렵다고 말했다.' WHERE id=3964;",
    "UPDATE words SET meaning='탕후루', example_zh='北京糖葫芦是一种受欢迎的传统零食。', example_ko='베이징 탕후루는 인기 있는 전통 간식이다.' WHERE id=3965;",
    "UPDATE words SET meaning='만약, 만일', example_zh='倘若明天下雨，活动就推迟举行。', example_ko='만약 내일 비가 오면 행사는 연기된다.' WHERE id=3966;",
    "UPDATE words SET meaning='꺼내다, 파다', example_zh='他从口袋里掏出了一把钥匙。', example_ko='그는 주머니에서 열쇠를 꺼냈다.' WHERE id=3967;",
    "UPDATE words SET meaning='말이 끊이지 않다', example_zh='他演讲时滔滔不绝，让听众折服。', example_ko='그는 연설할 때 말이 끊이지 않아서 청중을 감복시켰다.' WHERE id=3968;",
    "UPDATE words SET meaning='도자기', example_zh='景德镇的陶瓷举世闻名。', example_ko='징더전의 도자기는 세계적으로 유명하다.' WHERE id=3969;",
    "UPDATE words SET meaning='장난꾸러기다, 개구지다', example_zh='这个孩子很淘气，总是惹是生非。', example_ko='이 아이는 장난꾸러기라서 항상 말썽을 피운다.' WHERE id=3970;",
    "UPDATE words SET meaning='도태되다', example_zh='不适应环境变化的企业会被市场淘汰。', example_ko='환경 변화에 적응하지 못하는 기업은 시장에서 도태된다.' WHERE id=3971;",
    "UPDATE words SET meaning='흥정하다', example_zh='买东西时可以适当讨价还价。', example_ko='물건을 살 때 적당히 흥정할 수 있다.' WHERE id=3972;",
    "UPDATE words SET meaning='특기, 특장점', example_zh='她的特长是唱歌和跳舞。', example_ko='그녀의 특기는 노래와 춤이다.' WHERE id=3973;",
    "UPDATE words SET meaning='특정하다', example_zh='这项规定适用于特定的情况。', example_ko='이 규정은 특정한 상황에 적용된다.' WHERE id=3974;",
    "UPDATE words SET meaning='특색', example_zh='这道菜有鲜明的地方特色。', example_ko='이 요리는 선명한 지방 특색이 있다.' WHERE id=3975;",
    "UPDATE words SET meaning='발탁하다, 승진시키다', example_zh='他因工作出色而被提拔为部门经理。', example_ko='그는 업무가 뛰어나서 부서 경리로 발탁되었다.' WHERE id=3976;",
    "UPDATE words SET meaning='정제하다, 추출하다', example_zh='石油提炼后可以得到各种燃料。', example_ko='석유를 정제하면 각종 연료를 얻을 수 있다.' WHERE id=3977;",
    "UPDATE words SET meaning='힌트를 주다, 알려주다', example_zh='老师给出了一些提示，帮助学生解题。', example_ko='선생님이 학생들이 문제를 풀도록 힌트를 몇 가지 주었다.' WHERE id=3978;",
    "UPDATE words SET meaning='제의하다, 건의하다', example_zh='他提议在会议上讨论这个问题。', example_ko='그는 회의에서 이 문제를 토론할 것을 제의했다.' WHERE id=3979;",
    "UPDATE words SET meaning='소재, 제재', example_zh='这部电影的题材非常新颖，吸引了大量观众。', example_ko='이 영화의 소재가 매우 참신해서 많은 관객을 끌어들였다.' WHERE id=3980;",
    "UPDATE words SET meaning='이해하다, 배려하다', example_zh='我们应该互相体谅，理解彼此的难处。', example_ko='우리는 서로 이해하고 서로의 어려움을 배려해야 한다.' WHERE id=3981;",
    "UPDATE words SET meaning='체면, 의젓하다', example_zh='他处理事情有体面，让大家尊重。', example_ko='그는 일을 처리하는 방식이 의젓해서 모두의 존중을 받는다.' WHERE id=3982;",
    "UPDATE words SET meaning='체계', example_zh='完善的法律体系是法治社会的基础。', example_ko='완비된 법률 체계는 법치 사회의 기초다.' WHERE id=3983;",
    "UPDATE words SET meaning='천재', example_zh='他从小就被认为是数学天才。', example_ko='그는 어릴 때부터 수학 천재로 여겨졌다.' WHERE id=3984;",
    "UPDATE words SET meaning='가정의 화락', example_zh='一家人团聚，共享天伦之乐。', example_ko='온 가족이 모여 가정의 화락을 함께 누렸다.' WHERE id=3985;",
    "UPDATE words SET meaning='천연가스', example_zh='天然气是一种清洁能源。', example_ko='천연가스는 청정 에너지다.' WHERE id=3986;",
    "UPDATE words SET meaning='타고나다, 천성', example_zh='他天生就有音乐天赋。', example_ko='그는 타고난 음악적 재능이 있다.' WHERE id=3987;",
    "UPDATE words SET meaning='천당, 낙원', example_zh='她总是把这片美丽的土地称为人间天堂。', example_ko='그녀는 항상 이 아름다운 땅을 지상낙원이라고 부른다.' WHERE id=3988;",
    "UPDATE words SET meaning='천문학', example_zh='他对天文学充满了好奇和热情。', example_ko='그는 천문학에 대한 호기심과 열정이 가득하다.' WHERE id=3989;",
    "UPDATE words SET meaning='육상', example_zh='他参加了田径比赛，获得了金牌。', example_ko='그는 육상 경기에 참가해 금메달을 땄다.' WHERE id=3990;",
    "UPDATE words SET meaning='핥다', example_zh='小狗用舌头舔了舔主人的手。', example_ko='강아지가 혀로 주인의 손을 핥았다.' WHERE id=3991;",
    "UPDATE words SET meaning='까다롭다, 트집 잡다', example_zh='他对食物很挑剔，只吃特定的菜肴。', example_ko='그는 음식에 까다로워서 특정 요리만 먹는다.' WHERE id=3992;",
    "UPDATE words SET meaning='조항, 조목', example_zh='合同中的条款需要仔细审查。', example_ko='계약서의 조항은 꼼꼼히 심사해야 한다.' WHERE id=3993;",
    "UPDATE words SET meaning='조리, 논리', example_zh='他说话条理清晰，让人容易理解。', example_ko='그는 말할 때 조리가 분명해서 이해하기 쉽다.' WHERE id=3994;",
    "UPDATE words SET meaning='조약', example_zh='两国签署了贸易条约。', example_ko='양국이 무역 조약을 체결했다.' WHERE id=3995;",
    "UPDATE words SET meaning='조화롭게 하다, 중재하다', example_zh='他尝试调和双方的矛盾。', example_ko='그는 양측의 모순을 조화롭게 하려고 시도했다.' WHERE id=3996;",
    "UPDATE words SET meaning='조절하다, 배합하다', example_zh='工作和休息要合理调剂。', example_ko='일과 휴식을 합리적으로 조절해야 한다.' WHERE id=3997;",
    "UPDATE words SET meaning='조절하다', example_zh='空调可以调节室内温度。', example_ko='에어컨은 실내 온도를 조절할 수 있다.' WHERE id=3998;",
    "UPDATE words SET meaning='조정하다, 중재하다', example_zh='法院对双方的纠纷进行了调解。', example_ko='법원이 양측의 분쟁을 조정했다.' WHERE id=3999;",
    "UPDATE words SET meaning='양념, 조미료', example_zh='做菜要加适量的调料，才能增加风味。', example_ko='요리할 때 적당한 양의 조미료를 넣어야 맛이 좋아진다.' WHERE id=4000;",
    "UPDATE words SET meaning='이간질하다', example_zh='他总是挑拨朋友之间的关系。', example_ko='그는 항상 친구들 사이를 이간질한다.' WHERE id=4001;",
    "UPDATE words SET meaning='도발하다', example_zh='他的言论挑衅了对方，引发了争执。', example_ko='그의 언론이 상대방을 도발해서 분쟁을 일으켰다.' WHERE id=4002;",
    "UPDATE words SET meaning='뛰어오르다, 도약하다', example_zh='运动员在比赛中跳跃过了障碍物。', example_ko='선수가 경기에서 장애물을 뛰어넘었다.' WHERE id=4003;",
    "UPDATE words SET meaning='정박하다', example_zh='船只在港口停泊等待修理。', example_ko='선박이 항구에 정박해서 수리를 기다리고 있다.' WHERE id=4004;",
    "UPDATE words SET meaning='정돈하다, 멈추다', example_zh='他的演讲中有一段短暂的停顿。', example_ko='그의 연설에서 잠깐 멈추는 구간이 있었다.' WHERE id=4005;",
    "UPDATE words SET meaning='정체되다, 멈추다', example_zh='由于缺乏创新，这家公司的发展停滞了。', example_ko='혁신의 부족으로 이 회사의 발전이 정체되었다.' WHERE id=4006;",
    "UPDATE words SET meaning='정자', example_zh='公园里有一座古色古香的亭子。', example_ko='공원에 고풍스러운 정자가 있다.' WHERE id=4007;",
    "UPDATE words SET meaning='우뚝 솟다, 곧고 강하다', example_zh='这棵挺拔的松树已经生长了百年。', example_ko='이 우뚝 솟은 소나무는 이미 100년을 자랐다.' WHERE id=4008;",
    "UPDATE words SET meaning='통화', example_zh='通货膨胀导致物价上涨。', example_ko='통화 팽창으로 물가가 상승했다.' WHERE id=4009;",
    "UPDATE words SET meaning='통속적이다, 대중적이다', example_zh='这部电影通俗易懂，很受观众欢迎。', example_ko='이 영화는 이해하기 쉽고 대중적이어서 관객에게 인기가 많다.' WHERE id=4010;",
    "UPDATE words SET meaning='공통으로 사용하다', example_zh='这种充电器可以通用于多种设备。', example_ko='이 충전기는 여러 기기에 공통으로 사용할 수 있다.' WHERE id=4011;",
    "UPDATE words SET meaning='구리 광산', example_zh='这个地区有丰富的铜矿资源。', example_ko='이 지역에는 풍부한 구리 광산 자원이 있다.' WHERE id=4012;",
    "UPDATE words SET meaning='동포', example_zh='海外华人都是中华民族的同胞。', example_ko='해외 화교들은 모두 중화 민족의 동포다.' WHERE id=4013;",
    "UPDATE words SET meaning='동지', example_zh='革命时期，战友们互称同志。', example_ko='혁명 시기에 전우들은 서로를 동지라고 불렀다.' WHERE id=4014;",
    "UPDATE words SET meaning='동화', example_zh='孩子们最喜欢听童话故事了。', example_ko='아이들은 동화 이야기 듣는 것을 가장 좋아한다.' WHERE id=4015;",
    "UPDATE words SET meaning='전반적으로 기획하고 고려하다', example_zh='做计划要统筹兼顾各方面的需求。', example_ko='계획을 세울 때는 전반적으로 각 방면의 수요를 기획하고 고려해야 한다.' WHERE id=4016;",
    "UPDATE words SET meaning='통계', example_zh='统计数据显示，今年经济增长了百分之六。', example_ko='통계 자료에 따르면 올해 경제가 6% 성장했다.' WHERE id=4017;",
    "UPDATE words SET meaning='모두, 전부', example_zh='他把今天的作业统统做完了。', example_ko='그는 오늘의 숙제를 모두 끝냈다.' WHERE id=4018;",
    "UPDATE words SET meaning='투기하다', example_zh='他通过股市投机赚了很多钱。', example_ko='그는 주식 시장 투기로 많은 돈을 벌었다.' WHERE id=4019;",
    "UPDATE words SET meaning='투표하다', example_zh='每个公民都有权利参与投票选举。', example_ko='모든 시민은 투표 선거에 참여할 권리가 있다.' WHERE id=4020;",
    "UPDATE words SET meaning='항복하다', example_zh='敌方军队在包围下被迫投降。', example_ko='적군은 포위 속에서 어쩔 수 없이 항복했다.' WHERE id=4021;",
    "UPDATE words SET meaning='투척하다, 던지다', example_zh='运动员练习投掷标枪。', example_ko='선수가 창 던지기를 연습하고 있다.' WHERE id=4022;",
    "UPDATE words SET meaning='머리가 벗겨지다, 민둥민둥하다', example_zh='随着年龄增长，他的头发慢慢秃了。', example_ko='나이가 들면서 그의 머리카락이 천천히 빠졌다.' WHERE id=4023;",
    "UPDATE words SET meaning='돌파하다', example_zh='科学家在研究中取得了重大突破。', example_ko='과학자들이 연구에서 중요한 돌파구를 열었다.' WHERE id=4024;",
    "UPDATE words SET meaning='도안, 패턴', example_zh='这块布料上有精美的图案。', example_ko='이 천에는 정교한 도안이 있다.' WHERE id=4025;",
    "UPDATE words SET meaning='제자', example_zh='他收了几名徒弟，传授手艺。', example_ko='그는 제자 몇 명을 받아 손재주를 전수했다.' WHERE id=4026;",
    "UPDATE words SET meaning='경로, 방법', example_zh='找到解决问题的途径非常重要。', example_ko='문제를 해결하는 경로를 찾는 것이 매우 중요하다.' WHERE id=4027;",
    "UPDATE words SET meaning='바르다, 칠하다', example_zh='她在墙上涂抹了一层颜料。', example_ko='그녀는 벽에 물감을 한 층 발랐다.' WHERE id=4028;",
    "UPDATE words SET meaning='토양', example_zh='这片土地的土壤非常肥沃。', example_ko='이 땅의 토양은 매우 비옥하다.' WHERE id=4029;",
    "UPDATE words SET meaning='단결하다', example_zh='团结就是力量，我们要共同奋斗。', example_ko='단결은 힘이다, 우리는 함께 분투해야 한다.' WHERE id=4030;",
    "UPDATE words SET meaning='단체', example_zh='这个团体致力于保护环境。', example_ko='이 단체는 환경 보호에 헌신하고 있다.' WHERE id=4031;",
    "UPDATE words SET meaning='가족이 한데 모이다', example_zh='春节是家人团圆的重要时刻。', example_ko='춘절은 가족이 한데 모이는 중요한 순간이다.' WHERE id=4032;",
    "UPDATE words SET meaning='추측하다', example_zh='我推测他可能明天不会来。', example_ko='나는 그가 내일 오지 않을 것이라고 추측한다.' WHERE id=4033;",
    "UPDATE words SET meaning='뒤집다, 번복하다', example_zh='新的证据推翻了原来的判断。', example_ko='새로운 증거가 원래의 판단을 뒤집었다.' WHERE id=4034;",
    "UPDATE words SET meaning='추리하다', example_zh='侦探根据线索进行推理，找出了嫌疑人。', example_ko='탐정이 단서를 바탕으로 추리해서 용의자를 찾아냈다.' WHERE id=4035;",
    "UPDATE words SET meaning='추론하다', example_zh='他从实验数据中推论出了新的结论。', example_ko='그는 실험 데이터에서 새로운 결론을 추론해냈다.' WHERE id=4036;",
    "UPDATE words SET meaning='판촉하다, 영업하다', example_zh='公司派人到各地推销新产品。', example_ko='회사가 사람들을 각지에 파견해 신제품을 판촉하게 했다.' WHERE id=4037;",
    "UPDATE words SET meaning='삼키다', example_zh='他吞咽了一下，才开口说话。', example_ko='그는 침을 삼키고 나서야 말을 했다.' WHERE id=4038;",
    "UPDATE words SET meaning='분리하다, 벗어나다', example_zh='他终于脱离了那个困境。', example_ko='그는 마침내 그 곤경에서 벗어났다.' WHERE id=4039;",
    "UPDATE words SET meaning='미루다, 지연하다', example_zh='他总是拖延做作业，直到最后一刻才开始。', example_ko='그는 항상 숙제를 미루다가 마지막 순간이 되어서야 시작한다.' WHERE id=4040;",
    "UPDATE words SET meaning='탁송하다', example_zh='他将行李托运到目的地。', example_ko='그는 짐을 목적지까지 탁송했다.' WHERE id=4041;",
    "UPDATE words SET meaning='타당하다, 적절하다', example_zh='他的处理方式十分妥当。', example_ko='그의 처리 방식이 매우 타당하다.' WHERE id=4042;",
    "UPDATE words SET meaning='온당하다, 적절하다', example_zh='这件事处理得十分妥善。', example_ko='이 일은 매우 적절하게 처리되었다.' WHERE id=4043;",
    "UPDATE words SET meaning='타협하다', example_zh='经过长时间谈判，双方终于妥协了。', example_ko='오랜 협상 끝에 양측이 마침내 타협했다.' WHERE id=4044;",
    "UPDATE words SET meaning='타원형', example_zh='地球绕太阳的轨道是椭圆形的。', example_ko='지구가 태양을 도는 궤도는 타원형이다.' WHERE id=4045;",
    "UPDATE words SET meaning='침, 타액', example_zh='他紧张地咽了口唾沫。', example_ko='그는 긴장해서 침을 한 번 삼켰다.' WHERE id=4046;",
    "UPDATE words SET meaning='발굴하다', example_zh='考古学家挖掘出了古代文物。', example_ko='고고학자들이 고대 유물을 발굴했다.' WHERE id=4047;",
    "UPDATE words SET meaning='인형, 아기', example_zh='她买了一个可爱的娃娃送给孩子。', example_ko='그녀는 귀여운 인형을 사서 아이에게 주었다.' WHERE id=4048;",
    "UPDATE words SET meaning='무너지다, 분해되다', example_zh='强大的敌对势力在内部矛盾中瓦解了。', example_ko='강력한 적대 세력이 내부 모순으로 분해되었다.' WHERE id=4049;",
    "UPDATE words SET meaning='와 (감탄사)', example_zh='哇，这幅画真漂亮！', example_ko='와, 이 그림 정말 예쁘다!' WHERE id=4050;",
    "UPDATE words SET meaning='왜곡하다', example_zh='媒体歪曲了事实，引发了公众的不满。', example_ko='언론이 사실을 왜곡해서 대중의 불만을 일으켰다.' WHERE id=4051;",
    "UPDATE words SET meaning='외표, 겉모습', example_zh='不要只看外表，要看一个人的内在。', example_ko='겉모습만 보지 말고 사람의 내면을 봐야 한다.' WHERE id=4052;",
    "UPDATE words SET meaning='문외한, 비전문가', example_zh='我对这个领域完全是外行。', example_ko='나는 이 분야에서 완전히 문외한이다.' WHERE id=4053;",
    "UPDATE words SET meaning='외부 세계', example_zh='他长期与外界隔绝，对世界变化一无所知。', example_ko='그는 오랫동안 외부 세계와 단절되어 세상의 변화에 대해 아무것도 모른다.' WHERE id=4054;",
    "UPDATE words SET meaning='외향적이다', example_zh='她性格外向，在聚会上非常活跃。', example_ko='그녀는 외향적이어서 모임에서 매우 활발하다.' WHERE id=4055;",
    "UPDATE words SET meaning='환약', example_zh='医生给他开了一些消炎的药丸。', example_ko='의사가 그에게 염증을 없애는 환약을 처방했다.' WHERE id=4056;",
    "UPDATE words SET meaning='완비되다', example_zh='图书馆的设施完备，可以满足读者需求。', example_ko='도서관의 시설이 완비되어 독자들의 요구를 충족할 수 있다.' WHERE id=4057;",
    "UPDATE words SET meaning='완료되다, 끝나다', example_zh='工程按计划完毕，提前竣工了。', example_ko='공사가 계획대로 완료되어 예정보다 일찍 준공되었다.' WHERE id=4058;",
    "UPDATE words SET meaning='가지고 놀다, 희롱하다', example_zh='他玩弄感情，让女方很伤心。', example_ko='그는 감정을 희롱해서 여자 쪽을 매우 슬프게 했다.' WHERE id=4059;",
    "UPDATE words SET meaning='장난감, 물건', example_zh='这个孩子最喜欢的玩意儿是玩具车。', example_ko='이 아이가 가장 좋아하는 장난감은 장난감 차다.' WHERE id=4060;",
    "UPDATE words SET meaning='완고하다, 고집스럽다', example_zh='他非常顽固，不愿意接受新的想法。', example_ko='그는 매우 완고해서 새로운 생각을 받아들이려 하지 않는다.' WHERE id=4061;",
    "UPDATE words SET meaning='완강하다, 굳세다', example_zh='他凭借顽强的意志力克服了病痛。', example_ko='그는 완강한 의지력으로 병고를 극복했다.' WHERE id=4062;",
    "UPDATE words SET meaning='만회하다, 돌이키다', example_zh='虽然落后了，但他们仍然努力挽回局面。', example_ko='비록 뒤처졌지만 그들은 여전히 국면을 만회하려 노력했다.' WHERE id=4063;",
    "UPDATE words SET meaning='구하다, 살리다', example_zh='医生及时赶到，挽救了患者的生命。', example_ko='의사가 제때 도착해서 환자의 생명을 구했다.' WHERE id=4064;",
    "UPDATE words SET meaning='안타까워하다, 유감스러워하다', example_zh='他惋惜地说，这次机会真的错过了。', example_ko='그는 안타까워하며 이번 기회를 정말 놓쳤다고 말했다.' WHERE id=4065;",
    "UPDATE words SET meaning='매우, 극도로', example_zh='他对这次失败感到万分遗憾。', example_ko='그는 이번 실패에 극도로 유감스러워했다.' WHERE id=4066;",
    "UPDATE words SET meaning='평소, 예전', example_zh='他往常按时上班，今天却迟到了。', example_ko='그는 평소에 제때 출근하는데 오늘은 지각했다.' WHERE id=4067;",
    "UPDATE words SET meaning='옛일, 지난 일', example_zh='回忆往事，他感慨万千。', example_ko='옛일을 회상하며 그는 감회가 깊었다.' WHERE id=4068;",
    "UPDATE words SET meaning='네트워크, 인터넷', example_zh='网络技术的发展改变了我们的生活。', example_ko='인터넷 기술의 발전이 우리 삶을 바꿨다.' WHERE id=4069;",
    "UPDATE words SET meaning='망상하다, 헛된 꿈을 꾸다', example_zh='他妄想靠一夜暴富改变命运。', example_ko='그는 하룻밤 사이에 부자가 되어 운명을 바꾸겠다는 망상을 품었다.' WHERE id=4070;",
    "UPDATE words SET meaning='미미하다, 보잘것없다', example_zh='他的贡献虽然微不足道，但大家都很感激。', example_ko='그의 공헌은 보잘것없지만 모두들 매우 감사하게 생각한다.' WHERE id=4071;",
    "UPDATE words SET meaning='미시적, 미크로', example_zh='从微观角度看，这些分子的运动非常活跃。', example_ko='미시적 관점에서 보면 이 분자들의 운동은 매우 활발하다.' WHERE id=4072;",
    "UPDATE words SET meaning='위풍이 있다, 당당하다', example_zh='他穿着军服，威风凛凛地走进了大厅。', example_ko='그는 군복을 입고 위풍당당하게 홀에 들어왔다.' WHERE id=4073;",
    "UPDATE words SET meaning='위력', example_zh='这种新型武器的威力不可小觑。', example_ko='이 새로운 무기의 위력을 무시해서는 안 된다.' WHERE id=4074;",
    "UPDATE words SET meaning='위망, 명망', example_zh='他在公众中享有很高的威望。', example_ko='그는 대중에게 높은 명망을 누리고 있다.' WHERE id=4075;",
    "UPDATE words SET meaning='위신, 신용', example_zh='这件丑闻严重损害了他的威信。', example_ko='이 스캔들이 그의 위신을 심각하게 손상시켰다.' WHERE id=4076;",
    "UPDATE words SET meaning='위기', example_zh='公司面临严重的财务危机。', example_ko='회사가 심각한 재정 위기에 직면해 있다.' WHERE id=4077;",
    "UPDATE words SET meaning='위배하다, 어기다', example_zh='他的行为违背了道德准则。', example_ko='그의 행동은 도덕 기준에 위배된다.' WHERE id=4078;",
    "UPDATE words SET meaning='유지하다', example_zh='双方都希望维持良好的合作关系。', example_ko='양측 모두 좋은 협력 관계를 유지하기를 바란다.' WHERE id=4079;",
    "UPDATE words SET meaning='비타민', example_zh='多吃蔬菜和水果可以补充维生素。', example_ko='채소와 과일을 많이 먹으면 비타민을 보충할 수 있다.' WHERE id=4080;",
    "UPDATE words SET meaning='유지 보수하다', example_zh='公司定期对设备进行维修。', example_ko='회사는 정기적으로 설비를 유지 보수한다.' WHERE id=4081;",
    "UPDATE words SET meaning='오직, 유독', example_zh='班上唯独他没有参加这次活动。', example_ko='반에서 그만 유독 이번 활동에 참가하지 않았다.' WHERE id=4082;",
    "UPDATE words SET meaning='곤란하다, 어렵다', example_zh='他为一件小事感到为难，不知如何处理。', example_ko='그는 작은 일 때문에 어떻게 처리해야 할지 몰라 곤란해했다.' WHERE id=4083;",
    "UPDATE words SET meaning='기한을 정하다', example_zh='这项任务为期三个月，需要按时完成。', example_ko='이 임무는 3개월 기한으로 제때 완수해야 한다.' WHERE id=4084;",
    "UPDATE words SET meaning='수장이 되다, 으뜸이 되다', example_zh='他以为首的团队赢得了比赛。', example_ko='그를 수장으로 하는 팀이 대회에서 우승했다.' WHERE id=4085;",
]

with open('hsk6_data_3.sql', 'a', encoding='utf-8') as f:
    for line in lines:
        f.write(line + '\n')

print(f'Done, appended {len(lines)} lines')
