import io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

lines = [
    "UPDATE words SET meaning='용솟음치다, 쏟아져 나오다', example_zh='改革开放后，各种新思想涌现了出来。', example_ko='개혁개방 후 각종 새로운 생각이 쏟아져 나왔다.' WHERE id=4399;",
    "UPDATE words SET meaning='적극적으로 참가하다', example_zh='同学们踊跃参与了这次活动。', example_ko='동급생들이 이번 활동에 적극적으로 참가했다.' WHERE id=4400;",
    "UPDATE words SET meaning='공부를 열심히 하다', example_zh='他非常用功，每天学习十几个小时。', example_ko='그는 매우 열심히 공부해서 매일 십여 시간씩 학습한다.' WHERE id=4401;",
    "UPDATE words SET meaning='사용자', example_zh='这款软件的用户数量超过了一亿。', example_ko='이 소프트웨어의 사용자 수가 1억을 초과했다.' WHERE id=4402;",
    "UPDATE words SET meaning='적자생존', example_zh='市场竞争遵循优胜劣汰的原则。', example_ko='시장 경쟁은 적자생존의 원칙을 따른다.' WHERE id=4403;",
    "UPDATE words SET meaning='우선시하다', example_zh='公司优先考虑员工的安全问题。', example_ko='회사는 직원의 안전 문제를 우선시한다.' WHERE id=4404;",
    "UPDATE words SET meaning='우수하다', example_zh='他以优异的成绩毕业，获得了奖学金。', example_ko='그는 우수한 성적으로 졸업해서 장학금을 받았다.' WHERE id=4405;",
    "UPDATE words SET meaning='우월하다', example_zh='他生长在优越的环境中，受到了良好的教育。', example_ko='그는 우월한 환경에서 자라나 좋은 교육을 받았다.' WHERE id=4406;",
    "UPDATE words SET meaning='우울하다', example_zh='他最近忧郁，不知道是什么原因。', example_ko='그는 요즘 우울한데 이유를 모르겠다.' WHERE id=4407;",
    "UPDATE words SET meaning='기름지다', example_zh='他不喜欢吃油腻的食物，喜欢清淡的饮食。', example_ko='그는 기름진 음식을 싫어해서 담백한 식사를 좋아한다.' WHERE id=4408;",
    "UPDATE words SET meaning='페인트', example_zh='墙上的油漆已经开始剥落了。', example_ko='벽의 페인트가 이미 벗겨지기 시작했다.' WHERE id=4409;",
    "UPDATE words SET meaning='마치 ~와 같다', example_zh='她的笑容犹如春风，让人感到温暖。', example_ko='그녀의 미소는 마치 봄바람과 같아서 따뜻함을 느끼게 한다.' WHERE id=4410;",
    "UPDATE words SET meaning='조리 있다', example_zh='他做事有条不紊，效率很高。', example_ko='그는 일을 조리 있게 해서 효율이 매우 높다.' WHERE id=4411;",
    "UPDATE words SET meaning='유치하다', example_zh='这个想法太幼稚，需要更多思考。', example_ko='이 생각은 너무 유치해서 더 많은 생각이 필요하다.' WHERE id=4412;",
    "UPDATE words SET meaning='유혹하다', example_zh='甜食诱惑着他，让他很难坚持节食。', example_ko='단것이 그를 유혹해서 다이어트를 유지하기 어렵게 한다.' WHERE id=4413;",
    "UPDATE words SET meaning='어리석다', example_zh='做出这样愚蠢的决定，他后悔了很久。', example_ko='이런 어리석은 결정을 내린 것을 그는 오랫동안 후회했다.' WHERE id=4414;",
    "UPDATE words SET meaning='우매하다, 무지하다', example_zh='愚昧和无知是阻碍社会进步的障碍。', example_ko='우매함과 무지는 사회 발전을 가로막는 장애물이다.' WHERE id=4415;",
    "UPDATE words SET meaning='여론', example_zh='这件事引起了广泛的舆论关注。', example_ko='이 일이 광범위한 여론의 관심을 불러일으켰다.' WHERE id=4416;",
    "UPDATE words SET meaning='어민', example_zh='渔民们每天清晨出海捕鱼。', example_ko='어민들이 매일 새벽에 고기잡이를 하러 바다에 나간다.' WHERE id=4417;",
    "UPDATE words SET meaning='날로 증가하다', example_zh='城市化的进程中，人口密度与日俱增。', example_ko='도시화 과정에서 인구 밀도가 날로 증가하고 있다.' WHERE id=4418;",
    "UPDATE words SET meaning='다운 재킷', example_zh='冬天他穿着厚厚的羽绒服，非常保暖。', example_ko='겨울에 그는 두꺼운 다운 재킷을 입어서 매우 따뜻하다.' WHERE id=4419;",
    "UPDATE words SET meaning='주다, 부여하다', example_zh='政府予以支持，帮助了这个项目的发展。', example_ko='정부가 지원을 부여해서 이 프로젝트의 발전을 도왔다.' WHERE id=4420;",
    "UPDATE words SET meaning='점점 더, 더욱더', example_zh='随着时间流逝，他的技术愈来愈精湛。', example_ko='시간이 흐름에 따라 그의 기술이 점점 더 정교해졌다.' WHERE id=4421;",
    "UPDATE words SET meaning='예측하다', example_zh='他预料到了市场的变化，提前做了准备。', example_ko='그는 시장의 변화를 예측해서 미리 준비했다.' WHERE id=4422;",
    "UPDATE words SET meaning='예기하다', example_zh='这次会议的效果超出了预期。', example_ko='이번 회의의 효과는 예기를 초과했다.' WHERE id=4423;",
    "UPDATE words SET meaning='예선', example_zh='他通过了预赛，进入了决赛阶段。', example_ko='그는 예선을 통과해서 결선 단계에 진입했다.' WHERE id=4424;",
    "UPDATE words SET meaning='예산', example_zh='这个项目的预算超出了预期。', example_ko='이 프로젝트의 예산이 예기를 초과했다.' WHERE id=4425;",
    "UPDATE words SET meaning='미리, 사전에', example_zh='你应该预先做好充分的准备。', example_ko='미리 충분한 준비를 해야 한다.' WHERE id=4426;",
    "UPDATE words SET meaning='예언하다', example_zh='他预言了这场经济危机的到来。', example_ko='그는 이 경제 위기의 도래를 예언했다.' WHERE id=4427;",
    "UPDATE words SET meaning='전조, 징조', example_zh='乌云密布是暴风雨来临的预兆。', example_ko='구름이 잔뜩 끼는 것은 폭풍우가 올 징조다.' WHERE id=4428;",
    "UPDATE words SET meaning='욕망', example_zh='对权力的欲望有时会让人失去理智。', example_ko='권력에 대한 욕망은 때로 사람이 이성을 잃게 한다.' WHERE id=4429;",
    "UPDATE words SET meaning='우화', example_zh='《伊索寓言》是一部著名的寓言故事集。', example_ko='이솝 우화는 유명한 우화 이야기집이다.' WHERE id=4430;",
    "UPDATE words SET meaning='억울하다', example_zh='他受到了冤枉，感到十分委屈。', example_ko='그는 억울한 누명을 써서 매우 서러움을 느꼈다.' WHERE id=4431;",
    "UPDATE words SET meaning='원수, 국가 원수', example_zh='两国元首举行了会谈，讨论双边关系。', example_ko='양국 원수가 회담을 열어 양자 관계를 논의했다.' WHERE id=4432;",
    "UPDATE words SET meaning='원소', example_zh='水由氢和氧两种元素组成。', example_ko='물은 수소와 산소 두 원소로 이루어진다.' WHERE id=4433;",
    "UPDATE words SET meaning='정월 대보름', example_zh='元宵节是中国传统节日，有吃汤圆的习俗。', example_ko='정월 대보름은 중국 전통 명절로 탕위안을 먹는 풍습이 있다.' WHERE id=4434;",
    "UPDATE words SET meaning='원만하다, 완전하다', example_zh='这次活动圆满结束，大家都很满意。', example_ko='이번 행사가 원만하게 마무리되어서 모두 매우 만족한다.' WHERE id=4435;",
    "UPDATE words SET meaning='원고, 소송 제기자', example_zh='原告提出了赔偿申请。', example_ko='원고가 배상 신청을 제출했다.' WHERE id=4436;",
    "UPDATE words SET meaning='원리', example_zh='他学习了机器运作的基本原理。', example_ko='그는 기계 작동의 기본 원리를 배웠다.' WHERE id=4437;",
    "UPDATE words SET meaning='원시적이다', example_zh='这个地区保留了原始的自然风貌。', example_ko='이 지역은 원시적인 자연 경관을 보존하고 있다.' WHERE id=4438;",
    "UPDATE words SET meaning='원래, 처음에', example_zh='原先他打算去旅游，后来改变了计划。', example_ko='원래 그는 여행 가려 했는데 나중에 계획을 바꿨다.' WHERE id=4439;",
    "UPDATE words SET meaning='원림, 정원', example_zh='苏州园林是中国著名的历史景观。', example_ko='쑤저우 원림은 중국 유명한 역사 경관이다.' WHERE id=4440;",
    "UPDATE words SET meaning='원천', example_zh='知识是社会进步的源泉。', example_ko='지식은 사회 발전의 원천이다.' WHERE id=4441;",
    "UPDATE words SET meaning='구속하다', example_zh='合同对双方都有约束力。', example_ko='계약은 양측 모두에게 구속력이 있다.' WHERE id=4442;",
    "UPDATE words SET meaning='장인, 아내의 아버지', example_zh='他和岳父的关系非常融洽。', example_ko='그는 장인과 관계가 매우 화목하다.' WHERE id=4443;",
    "UPDATE words SET meaning='악보', example_zh='他从小学习乐谱，掌握了多种乐器。', example_ko='그는 어릴 때부터 악보를 배워서 여러 악기를 익혔다.' WHERE id=4444;",
    "UPDATE words SET meaning='다리미질하다', example_zh='她把衣服熨得平整，出门时很精神。', example_ko='그녀는 옷을 다리미질해서 반듯하게 만들어 외출 시 말끔하다.' WHERE id=4445;",
    "UPDATE words SET meaning='내재되어 있다', example_zh='这片土地蕴藏着丰富的矿产资源。', example_ko='이 땅에는 풍부한 광물 자원이 내재되어 있다.' WHERE id=4446;",
    "UPDATE words SET meaning='계산하다', example_zh='计算机能够快速完成复杂的运算。', example_ko='컴퓨터는 복잡한 계산을 빠르게 완수할 수 있다.' WHERE id=4447;",
    "UPDATE words SET meaning='운행하다', example_zh='这列火车每天运行两趟。', example_ko='이 기차는 매일 두 번 운행한다.' WHERE id=4448;",
    "UPDATE words SET meaning='양조하다, 조성하다', example_zh='这件事酝酿了很久，终于爆发了。', example_ko='이 일이 오랫동안 조성되다가 결국 폭발했다.' WHERE id=4449;",
    "UPDATE words SET meaning='임신하다, 낳다', example_zh='这片土地孕育了灿烂的古代文明。', example_ko='이 땅이 찬란한 고대 문명을 낳았다.' WHERE id=4450;",
    "UPDATE words SET meaning='내려치다, 박살내다', example_zh='他一拳砸碎了玻璃。', example_ko='그는 주먹으로 유리를 박살냈다.' WHERE id=4451;",
    "UPDATE words SET meaning='잡기', example_zh='她从小就学习杂技，现在是一名表演者。', example_ko='그녀는 어릴 때부터 잡기를 배워서 지금은 공연자가 되었다.' WHERE id=4452;",
    "UPDATE words SET meaning='교배하다, 혼혈', example_zh='这种新品种是通过杂交培育出来的。', example_ko='이 새 품종은 교배를 통해 육성된 것이다.' WHERE id=4453;",
    "UPDATE words SET meaning='어떻게', example_zh='你咋了，脸色这么难看？', example_ko='너 어떻게 된 거야, 얼굴색이 이렇게 나빠?' WHERE id=4454;",
    "UPDATE words SET meaning='재난', example_zh='这次灾难造成了大量人员伤亡。', example_ko='이번 재난으로 많은 인명 피해가 발생했다.' WHERE id=4455;",
    "UPDATE words SET meaning='재배하다, 육성하다', example_zh='农民精心栽培了各种蔬菜。', example_ko='농부가 각종 채소를 정성껏 재배했다.' WHERE id=4456;",
    "UPDATE words SET meaning='잡다, 도살하다', example_zh='他在集市上宰了一只鸡。', example_ko='그는 시장에서 닭 한 마리를 잡았다.' WHERE id=4457;",
    "UPDATE words SET meaning='개의하다, 마음에 두다', example_zh='他根本不在乎别人的看法。', example_ko='그는 전혀 다른 사람들의 시각을 개의하지 않는다.' WHERE id=4458;",
    "UPDATE words SET meaning='신경 쓰다', example_zh='她非常在意自己的外貌，每天花大量时间打扮。', example_ko='그녀는 자신의 외모에 매우 신경 써서 매일 많은 시간을 꾸미는 데 쓴다.' WHERE id=4459;",
    "UPDATE words SET meaning='거듭 분발하다', example_zh='经历了失败后，他再接再厉，终于成功了。', example_ko='실패를 경험한 후 그는 거듭 분발해서 결국 성공했다.' WHERE id=4460;",
    "UPDATE words SET meaning='모으다, 저축하다', example_zh='他辛苦工作了十年，终于攒够了买房的钱。', example_ko='그는 10년 동안 열심히 일해서 결국 집을 살 돈을 모았다.' WHERE id=4461;",
    "UPDATE words SET meaning='감탄하다', example_zh='大家都赞叹这幅画的精美。', example_ko='모두들 이 그림의 정교함에 감탄했다.' WHERE id=4462;",
    "UPDATE words SET meaning='찬동하다', example_zh='他赞同这项提议，表示支持。', example_ko='그는 이 제안에 찬동하며 지지를 표명했다.' WHERE id=4463;",
    "UPDATE words SET meaning='찬양하다', example_zh='他的事迹受到了大家的赞扬。', example_ko='그의 업적은 모두의 찬양을 받았다.' WHERE id=4464;",
    "UPDATE words SET meaning='지원하다, 후원하다', example_zh='这家公司赞助了多个公益活动。', example_ko='이 회사는 여러 공익 활동을 지원했다.' WHERE id=4465;",
    "UPDATE words SET meaning='잠시, 우선', example_zh='我们暂且不讨论这个问题，先处理其他事情。', example_ko='우리는 잠시 이 문제를 토론하지 말고 먼저 다른 일을 처리하자.' WHERE id=4466;",
    "UPDATE words SET meaning='망가뜨리다', example_zh='他不小心糟蹋了一批食材。', example_ko='그는 실수로 식재료를 한 묶음 망가뜨렸다.' WHERE id=4467;",
    "UPDATE words SET meaning='당하다', example_zh='他在这次事故中遭受了严重伤害。', example_ko='그는 이번 사고에서 심각한 부상을 당했다.' WHERE id=4468;",
    "UPDATE words SET meaning='재앙을 당하다', example_zh='无辜的人在战争中遭殃，十分可怜。', example_ko='무고한 사람들이 전쟁에서 재앙을 당하니 매우 불쌍하다.' WHERE id=4469;",
    "UPDATE words SET meaning='처하다, 맞닥뜨리다', example_zh='他遭遇了职业生涯中最大的挫折。', example_ko='그는 직업 생애에서 가장 큰 좌절을 맞닥뜨렸다.' WHERE id=4470;",
    "UPDATE words SET meaning='반란을 일으키다', example_zh='历史上，农民因无法忍受压迫而造反。', example_ko='역사적으로 농민들은 압박을 견디지 못해 반란을 일으켰다.' WHERE id=4471;",
    "UPDATE words SET meaning='조형하다', example_zh='艺术家精心设计了这件作品的造型。', example_ko='예술가가 이 작품의 조형을 정성껏 디자인했다.' WHERE id=4472;",
    "UPDATE words SET meaning='소음', example_zh='这个城市的噪音污染越来越严重。', example_ko='이 도시의 소음 오염이 점점 심각해지고 있다.' WHERE id=4473;",
    "UPDATE words SET meaning='탓하다', example_zh='这次失误不能全责怪他一个人。', example_ko='이번 실수를 그 한 사람에게만 전부 탓할 수 없다.' WHERE id=4474;",
    "UPDATE words SET meaning='도둑', example_zh='警察抓住了那名入室行窃的贼。', example_ko='경찰이 침입 절도한 도둑을 잡았다.' WHERE id=4475;",
    "UPDATE words SET meaning='더하다, 추가하다', example_zh='他为这个团队增添了新的活力。', example_ko='그는 이 팀에 새로운 활력을 더했다.' WHERE id=4476;",
    "UPDATE words SET meaning='선물하다', example_zh='他赠送了一本书给朋友作为生日礼物。', example_ko='그는 친구에게 생일 선물로 책 한 권을 선물했다.' WHERE id=4477;",
    "UPDATE words SET meaning='찌꺼기', example_zh='喝完茶后，杯底留下了一些茶渣。', example_ko='차를 다 마신 후 잔 바닥에 찻잎 찌꺼기가 남았다.' WHERE id=4478;",
    "UPDATE words SET meaning='찌르다, 꽂다', example_zh='她把花枝扎进了花瓶里。', example_ko='그녀는 꽃가지를 꽃병에 꽂았다.' WHERE id=4479;",
    "UPDATE words SET meaning='탄탄하다, 착실하다', example_zh='他的基础非常扎实，学起来很快。', example_ko='그의 기초가 매우 탄탄해서 배우는 속도가 빠르다.' WHERE id=4480;",
    "UPDATE words SET meaning='눈을 깜빡이다', example_zh='他紧张地眨了眨眼睛。', example_ko='그는 긴장해서 눈을 깜빡였다.' WHERE id=4481;",
    "UPDATE words SET meaning='사기치다', example_zh='他被一个陌生人诈骗了一大笔钱。', example_ko='그는 낯선 사람에게 많은 돈을 사기당했다.' WHERE id=4482;",
    "UPDATE words SET meaning='요약, 초록', example_zh='请将这篇文章写成一份摘要。', example_ko='이 글을 요약문으로 작성해 주세요.' WHERE id=4483;",
    "UPDATE words SET meaning='채권', example_zh='政府发行了国债债券，筹集资金。', example_ko='정부가 국채 채권을 발행해서 자금을 조달했다.' WHERE id=4484;",
    "UPDATE words SET meaning='덕을 보다', example_zh='他沾光了朋友的关系，找到了好工作。', example_ko='그는 친구 관계 덕을 보아 좋은 직장을 찾았다.' WHERE id=4485;",
    "UPDATE words SET meaning='우러러 보다', example_zh='他们去瞻仰了烈士纪念碑。', example_ko='그들은 열사 기념비를 우러러 보러 갔다.' WHERE id=4486;",
    "UPDATE words SET meaning='단호하다', example_zh='他斩钉截铁地拒绝了这个不合理的要求。', example_ko='그는 단호하게 이 불합리한 요구를 거절했다.' WHERE id=4487;",
    "UPDATE words SET meaning='전시하다', example_zh='博物馆展示了大量珍贵的历史文物。', example_ko='박물관이 많은 귀한 역사 유물을 전시했다.' WHERE id=4488;",
    "UPDATE words SET meaning='전망하다', example_zh='他对未来充满信心，展望着更好的明天。', example_ko='그는 미래에 대한 자신감이 가득해서 더 나은 내일을 전망하고 있다.' WHERE id=4489;",
    "UPDATE words SET meaning='나타내다, 드러내다', example_zh='这幅画展现了大自然的壮丽景色。', example_ko='이 그림은 자연의 웅장한 경치를 드러냈다.' WHERE id=4490;",
    "UPDATE words SET meaning='새롭다', example_zh='他的观点崭新，让人耳目一新。', example_ko='그의 관점이 새로워서 신선함을 느끼게 한다.' WHERE id=4491;",
    "UPDATE words SET meaning='전투하다', example_zh='战士们在战场上英勇战斗。', example_ko='전사들이 전장에서 영용하게 전투했다.' WHERE id=4492;",
    "UPDATE words SET meaning='전략', example_zh='制定合理的战略是赢得竞争的关键。', example_ko='합리적인 전략을 수립하는 것이 경쟁에서 이기는 핵심이다.' WHERE id=4493;",
    "UPDATE words SET meaning='전술', example_zh='教练调整了比赛的战术，帮助球队取得了胜利。', example_ko='코치가 경기 전술을 조정해서 팀이 승리를 거두도록 도왔다.' WHERE id=4494;",
    "UPDATE words SET meaning='전역', example_zh='这次战役持续了数月，最终获得了胜利。', example_ko='이번 전역은 수개월간 지속되어 결국 승리를 거뒀다.' WHERE id=4495;",
    "UPDATE words SET meaning='점거하다', example_zh='敌人占据了这座城市，并加强了防守。', example_ko='적이 이 도시를 점거하고 방어를 강화했다.' WHERE id=4496;",
    "UPDATE words SET meaning='점령하다', example_zh='军队占领了战略要地。', example_ko='군대가 전략적 요지를 점령했다.' WHERE id=4497;",
    "UPDATE words SET meaning='점유하다', example_zh='这家公司占有了大部分的市场份额。', example_ko='이 회사는 시장 점유율의 대부분을 차지하고 있다.' WHERE id=4498;",
    "UPDATE words SET meaning='장정, 규정', example_zh='公司章程规定了员工的权利和义务。', example_ko='회사 규정은 직원의 권리와 의무를 규정했다.' WHERE id=4499;",
    "UPDATE words SET meaning='어른, 윗사람', example_zh='对长辈要保持尊敬，这是基本礼貌。', example_ko='어른에게 공경을 유지하는 것이 기본 예의다.' WHERE id=4500;",
    "UPDATE words SET meaning='장애', example_zh='他克服了重重障碍，最终实现了目标。', example_ko='그는 겹겹의 장애를 극복해서 결국 목표를 실현했다.' WHERE id=4501;",
    "UPDATE words SET meaning='텐트', example_zh='他们搭帐篷，在野外露营。', example_ko='그들은 텐트를 치고 야외에서 캠핑했다.' WHERE id=4502;",
    "UPDATE words SET meaning='모집하다', example_zh='公司正在招收新的员工。', example_ko='회사가 새 직원을 모집하고 있다.' WHERE id=4503;",
    "UPDATE words SET meaning='입찰 공고하다', example_zh='政府发布了招投标公告，吸引了大量企业参与。', example_ko='정부가 입찰 공고를 발표해서 많은 기업의 참여를 끌어들였다.' WHERE id=4504;",
    "UPDATE words SET meaning='활기차다', example_zh='年轻人朝气蓬勃，充满了活力。', example_ko='젊은이들이 활기차게 활력이 넘친다.' WHERE id=4505;",
    "UPDATE words SET meaning='매혹되다', example_zh='他对这部小说着迷，一读就是一整天。', example_ko='그는 이 소설에 매혹되어서 한 번 읽으면 하루 종일 읽는다.' WHERE id=4506;",
    "UPDATE words SET meaning='늪지대', example_zh='沼泽地区的生态系统非常脆弱。', example_ko='늪지대의 생태계는 매우 취약하다.' WHERE id=4507;",
    "UPDATE words SET meaning='돌보다', example_zh='她精心照料着家里的老人和孩子。', example_ko='그녀는 집의 노인과 아이들을 정성껏 돌봤다.' WHERE id=4508;",
    "UPDATE words SET meaning='여전히, 예전과 같이', example_zh='尽管失败了，他照样继续努力。', example_ko='비록 실패했지만 그는 여전히 계속 노력한다.' WHERE id=4509;",
    "UPDATE words SET meaning='비추다', example_zh='阳光照耀着大地，带来了温暖。', example_ko='햇빛이 대지를 비추어서 따뜻함을 가져온다.' WHERE id=4510;",
    "UPDATE words SET meaning='호응하다, 맞게 하다', example_zh='这次活动前后照应，组织得很好。', example_ko='이번 행사는 앞뒤가 잘 호응되어 잘 조직되었다.' WHERE id=4511;",
    "UPDATE words SET meaning='막다', example_zh='大树遮挡了阳光，使这里很凉爽。', example_ko='큰 나무가 햇빛을 막아서 이곳이 매우 시원하다.' WHERE id=4512;",
    "UPDATE words SET meaning='뒤흔들다, 고생시키다', example_zh='这次手术折腾了他好几天。', example_ko='이번 수술이 그를 여러 날 동안 고생시켰다.' WHERE id=4513;",
    "UPDATE words SET meaning='꺾이다, 할인하다', example_zh='这件商品打了折扣，比原价便宜了很多。', example_ko='이 상품은 할인이 되어서 원가보다 많이 싸졌다.' WHERE id=4514;",
    "UPDATE words SET meaning='고통을 주다, 시달리다', example_zh='疾病折磨着他，让他痛苦不堪。', example_ko='질병이 그를 시달리게 해서 고통스럽기 그지없다.' WHERE id=4515;",
    "UPDATE words SET meaning='진상, 실상', example_zh='他终于查明了事件的真相。', example_ko='그는 마침내 사건의 진상을 밝혀냈다.' WHERE id=4516;",
    "UPDATE words SET meaning='진지하다', example_zh='他对工作的态度非常真挚。', example_ko='그의 일에 대한 태도는 매우 진지하다.' WHERE id=4517;",
    "UPDATE words SET meaning='귀중하다', example_zh='这些文物非常珍贵，需要妥善保护。', example_ko='이 유물들은 매우 귀중해서 적절하게 보호해야 한다.' WHERE id=4518;",
    "UPDATE words SET meaning='희귀하다', example_zh='这种珍稀动物面临灭绝的危险。', example_ko='이 희귀 동물은 멸종 위기에 처해 있다.' WHERE id=4519;",
    "UPDATE words SET meaning='진주', example_zh='她佩戴了一串美丽的珍珠项链。', example_ko='그녀는 아름다운 진주 목걸이를 걸었다.' WHERE id=4520;",
    "UPDATE words SET meaning='형사, 탐정', example_zh='他是一名经验丰富的侦探。', example_ko='그는 경험이 풍부한 탐정이다.' WHERE id=4521;",
    "UPDATE words SET meaning='따져보다, 신중히 생각하다', example_zh='我们需要斟酌一下这个方案的可行性。', example_ko='우리는 이 방안의 실행 가능성을 신중히 따져봐야 한다.' WHERE id=4522;",
    "UPDATE words SET meaning='진지, 거점', example_zh='战士们坚守阵地，抵抗了敌人的进攻。', example_ko='전사들이 진지를 굳게 지키며 적의 공격에 저항했다.' WHERE id=4523;",
    "UPDATE words SET meaning='진용', example_zh='这支球队的阵容非常强大。', example_ko='이 팀의 진용은 매우 강하다.' WHERE id=4524;",
    "UPDATE words SET meaning='침착하다', example_zh='面对危险，他表现得非常镇定。', example_ko='위험에 직면해서 그는 매우 침착하게 행동했다.' WHERE id=4525;",
    "UPDATE words SET meaning='진정하다', example_zh='请镇静，不要慌张，慢慢解释清楚。', example_ko='진정하세요, 허둥대지 말고 천천히 설명해 주세요.' WHERE id=4526;",
    "UPDATE words SET meaning='진압하다', example_zh='警察迅速镇压了暴乱。', example_ko='경찰이 신속하게 폭동을 진압했다.' WHERE id=4527;",
    "UPDATE words SET meaning='힘이 솟다, 격려하다', example_zh='他的鼓励振奋了整个团队的士气。', example_ko='그의 격려가 팀 전체의 사기를 북돋웠다.' WHERE id=4528;",
    "UPDATE words SET meaning='진흥하다', example_zh='政府出台政策振兴了农村经济。', example_ko='정부가 농촌 경제를 진흥하는 정책을 내놓았다.' WHERE id=4529;",
    "UPDATE words SET meaning='놀라다', example_zh='这个消息震惊了整个世界。', example_ko='이 소식이 전 세계를 놀라게 했다.' WHERE id=4530;",
    "UPDATE words SET meaning='분쟁, 다툼', example_zh='两国之间的争端需要通过谈判解决。', example_ko='양국 간의 분쟁은 협상으로 해결해야 한다.' WHERE id=4531;",
    "UPDATE words SET meaning='쟁탈하다', example_zh='球队为了冠军奖杯拼命争夺。', example_ko='팀이 우승 트로피를 위해 온 힘을 다해 쟁탈했다.' WHERE id=4532;",
    "UPDATE words SET meaning='기를 살리다', example_zh='他完成了这项艰巨的任务，为家人争气。', example_ko='그는 이 어려운 임무를 완수해서 가족을 위해 기를 살렸다.' WHERE id=4533;",
    "UPDATE words SET meaning='앞다투어, 너도나도', example_zh='听到消息，学生们争先恐后地报名参加。', example_ko='소식을 듣고 학생들이 너도나도 신청에 참가했다.' WHERE id=4534;",
    "UPDATE words SET meaning='논쟁하다', example_zh='这个问题一直存在争议，没有定论。', example_ko='이 문제는 줄곧 논쟁이 있어서 정론이 없다.' WHERE id=4535;",
    "UPDATE words SET meaning='증발하다', example_zh='水在加热后会蒸发成水蒸气。', example_ko='물은 가열하면 수증기로 증발한다.' WHERE id=4536;",
    "UPDATE words SET meaning='정복하다', example_zh='他征服了世界最高峰，创造了奇迹。', example_ko='그는 세계 최고봉을 정복해서 기적을 만들었다.' WHERE id=4537;",
    "UPDATE words SET meaning='징수하다', example_zh='政府对进口商品征收了关税。', example_ko='정부가 수입 상품에 관세를 징수했다.' WHERE id=4538;",
    "UPDATE words SET meaning='정월', example_zh='正月初一是中国传统新年的第一天。', example_ko='정월 초하루는 중국 전통 새해의 첫날이다.' WHERE id=4539;",
    "UPDATE words SET meaning='발버둥 치다', example_zh='他在困境中挣扎，寻找出路。', example_ko='그는 곤경 속에서 발버둥 치며 출구를 찾고 있다.' WHERE id=4540;",
    "UPDATE words SET meaning='정비하다', example_zh='政府整顿了市场秩序，打击了违规行为。', example_ko='정부가 시장 질서를 정비하고 위규 행위를 단속했다.' WHERE id=4541;",
    "UPDATE words SET meaning='정당하다', example_zh='他的行为是正当的，符合法律规定。', example_ko='그의 행동은 정당해서 법률 규정에 부합한다.' WHERE id=4542;",
    "UPDATE words SET meaning='양수와 음수', example_zh='正负两极是电路的基本组成部分。', example_ko='양극과 음극은 회로의 기본 구성 요소다.' WHERE id=4543;",
    "UPDATE words SET meaning='정규적이다', example_zh='他接受了正规的职业培训。', example_ko='그는 정규적인 직업 교육을 받았다.' WHERE id=4544;",
    "UPDATE words SET meaning='점잖다, 착실하다', example_zh='他是一个正经人，不会做不合规矩的事情。', example_ko='그는 점잖은 사람이라 규칙에 맞지 않는 일을 하지 않는다.' WHERE id=4545;",
    "UPDATE words SET meaning='바른 기운', example_zh='历史上，有正气的人总是受人尊敬。', example_ko='역사적으로 바른 기운이 있는 사람은 항상 사람들의 존경을 받는다.' WHERE id=4546;",
    "UPDATE words SET meaning='정의', example_zh='维护正义是每个公民的责任。', example_ko='정의를 지키는 것은 모든 시민의 책임이다.' WHERE id=4547;",
    "UPDATE words SET meaning='정권', example_zh='新的政权建立后，立即推行了一系列改革。', example_ko='새 정권이 수립된 후 즉시 일련의 개혁을 추진했다.' WHERE id=4548;",
    "UPDATE words SET meaning='증명하다', example_zh='证据证实了他是无辜的。', example_ko='증거가 그가 무고함을 증명했다.' WHERE id=4549;",
    "UPDATE words SET meaning='증서, 증명서', example_zh='他拿到了职业资格证书，可以独立执业了。', example_ko='그는 직업 자격 증서를 받아서 독립적으로 일할 수 있게 되었다.' WHERE id=4550;",
    "UPDATE words SET meaning='신중하다', example_zh='做决定时要郑重考虑各种因素。', example_ko='결정을 내릴 때는 신중하게 각종 요소를 고려해야 한다.' WHERE id=4551;",
    "UPDATE words SET meaning='증상', example_zh='医生根据症状判断了病情。', example_ko='의사가 증상에 근거해서 병세를 판단했다.' WHERE id=4552;",
    "UPDATE words SET meaning='나뭇가지', example_zh='树枝上开满了美丽的花朵。', example_ko='나뭇가지에 아름다운 꽃들이 가득 피었다.' WHERE id=4553;",
    "UPDATE words SET meaning='지지하다, 버티다', example_zh='这根柱子支撑着整栋建筑。', example_ko='이 기둥이 건물 전체를 지지하고 있다.' WHERE id=4554;",
    "UPDATE words SET meaning='지출', example_zh='公司的支出超过了收入，面临财务危机。', example_ko='회사의 지출이 수입을 초과해서 재정 위기에 직면했다.' WHERE id=4555;",
    "UPDATE words SET meaning='지류', example_zh='这条支流汇入了主干河流。', example_ko='이 지류가 본류로 합류했다.' WHERE id=4556;",
    "UPDATE words SET meaning='지배하다, 배분하다', example_zh='金钱不应该支配人的生活。', example_ko='돈이 사람의 삶을 지배해서는 안 된다.' WHERE id=4557;",
    "UPDATE words SET meaning='지원하다', example_zh='友军及时赶来支援，扭转了战局。', example_ko='우방 군대가 제때 지원하러 와서 전국을 뒤집었다.' WHERE id=4558;",
    "UPDATE words SET meaning='지주, 기둥', example_zh='他是家庭的支柱，承担着所有责任。', example_ko='그는 가정의 기둥으로 모든 책임을 짊어지고 있다.' WHERE id=4559;",
    "UPDATE words SET meaning='지각', example_zh='他的知觉非常敏锐，能感受到细微的变化。', example_ko='그의 지각은 매우 예민해서 미세한 변화를 감지할 수 있다.' WHERE id=4560;",
    "UPDATE words SET meaning='만족하면 항상 즐겁다', example_zh='他信奉知足常乐的生活哲学。', example_ko='그는 만족하면 항상 즐겁다는 인생 철학을 신봉한다.' WHERE id=4561;",
    "UPDATE words SET meaning='지방', example_zh='摄入过多脂肪会导致肥胖。', example_ko='지방을 너무 많이 섭취하면 비만을 초래할 수 있다.' WHERE id=4562;",
    "UPDATE words SET meaning='생방송하다', example_zh='这场比赛将于明晚直播。', example_ko='이 경기는 내일 밤 생방송될 예정이다.' WHERE id=4563;",
    "UPDATE words SET meaning='당직하다', example_zh='他今晚值班，不能回家。', example_ko='그는 오늘 밤 당직이라서 집에 돌아갈 수 없다.' WHERE id=4564;",
    "UPDATE words SET meaning='식민지', example_zh='历史上，许多亚洲国家曾沦为殖民地。', example_ko='역사적으로 많은 아시아 나라들이 식민지가 된 적이 있다.' WHERE id=4565;",
    "UPDATE words SET meaning='직능', example_zh='每个部门都有其独特的职能。', example_ko='각 부서마다 독특한 직능이 있다.' WHERE id=4566;",
    "UPDATE words SET meaning='직위', example_zh='他升职后，职位变得更加重要。', example_ko='그는 승진 후 직위가 더욱 중요해졌다.' WHERE id=4567;",
    "UPDATE words SET meaning='직무', example_zh='他认真履行了自己的职务。', example_ko='그는 자신의 직무를 성실히 이행했다.' WHERE id=4568;",
    "UPDATE words SET meaning='지표', example_zh='这个指标是衡量企业绩效的重要依据。', example_ko='이 지표는 기업 성과를 측정하는 중요한 근거다.' WHERE id=4569;",
    "UPDATE words SET meaning='지정하다', example_zh='政府指定了特定区域进行开发建设。', example_ko='정부가 특정 구역을 개발 건설하도록 지정했다.' WHERE id=4570;",
    "UPDATE words SET meaning='손톱', example_zh='她把指甲涂成了红色，非常漂亮。', example_ko='그녀는 손톱을 빨간색으로 칠하니 매우 예쁘다.' WHERE id=4571;",
    "UPDATE words SET meaning='지령, 명령', example_zh='他按照上级的指令完成了任务。', example_ko='그는 상급의 지령에 따라 임무를 완수했다.' WHERE id=4572;",
    "UPDATE words SET meaning='나침반', example_zh='航海时，指南针是必不可少的工具。', example_ko='항해할 때 나침반은 없어서는 안 될 도구다.' WHERE id=4573;",
    "UPDATE words SET meaning='지시하다', example_zh='上级指示他立即前往现场处理问题。', example_ko='상급이 그에게 즉시 현장에 가서 문제를 처리하라고 지시했다.' WHERE id=4574;",
    "UPDATE words SET meaning='기대다', example_zh='他指望家人的支持，完成这个项目。', example_ko='그는 가족의 지원에 기대어 이 프로젝트를 완수한다.' WHERE id=4575;",
    "UPDATE words SET meaning='비판하다', example_zh='他的行为受到了大家的指责。', example_ko='그의 행동은 모두의 비판을 받았다.' WHERE id=4576;",
    "UPDATE words SET meaning='치안', example_zh='警察维护了社区的治安秩序。', example_ko='경찰이 커뮤니티의 치안 질서를 유지했다.' WHERE id=4577;",
    "UPDATE words SET meaning='다스리다, 처리하다', example_zh='政府采取了一系列措施治理环境污染。', example_ko='정부가 환경 오염을 처리하는 일련의 조치를 취했다.' WHERE id=4578;",
    "UPDATE words SET meaning='제재하다', example_zh='国际社会对这个国家实施了经济制裁。', example_ko='국제 사회가 이 나라에 경제 제재를 실시했다.' WHERE id=4579;",
    "UPDATE words SET meaning='제정하다', example_zh='政府制订了新的环保法规。', example_ko='정부가 새 환경보호 법규를 제정했다.' WHERE id=4580;",
    "UPDATE words SET meaning='제복', example_zh='士兵穿着整齐的制服，威风凛凛。', example_ko='병사가 단정한 제복을 입으니 위풍당당하다.' WHERE id=4581;",
    "UPDATE words SET meaning='제약하다', example_zh='资金短缺制约了这个项目的发展。', example_ko='자금 부족이 이 프로젝트의 발전을 제약했다.' WHERE id=4582;",
    "UPDATE words SET meaning='제지하다', example_zh='警察及时制止了这场冲突。', example_ko='경찰이 제때 이 충돌을 제지했다.' WHERE id=4583;",
    "UPDATE words SET meaning='인사말하다', example_zh='他在开幕式上致辞，欢迎来宾。', example_ko='그는 개막식에서 인사말을 하며 내빈을 환영했다.' WHERE id=4584;",
    "UPDATE words SET meaning='~에 힘쓰다', example_zh='他致力于改善社区的生活条件。', example_ko='그는 커뮤니티의 생활 조건 개선에 힘쓴다.' WHERE id=4585;",
    "UPDATE words SET meaning='~을 초래하다', example_zh='他的疏忽致使公司损失了大量资金。', example_ko='그의 소홀함이 회사로 하여금 많은 자금을 손실하게 초래했다.' WHERE id=4586;",
    "UPDATE words SET meaning='지력', example_zh='通过教育可以提高人的智力水平。', example_ko='교육을 통해 사람의 지력 수준을 높일 수 있다.' WHERE id=4587;",
    "UPDATE words SET meaning='지능', example_zh='人工智能模拟人类的智能进行决策。', example_ko='인공지능은 인간의 지능을 모방해서 결정을 내린다.' WHERE id=4588;",
    "UPDATE words SET meaning='지능 지수', example_zh='智商高不代表一定会成功，情商同样重要。', example_ko='지능 지수가 높다고 반드시 성공하는 것은 아니며 감성 지수도 똑같이 중요하다.' WHERE id=4589;",
    "UPDATE words SET meaning='체류하다', example_zh='由于护照问题，他在机场滞留了数小时。', example_ko='여권 문제로 그는 공항에서 몇 시간 동안 체류했다.' WHERE id=4590;",
    "UPDATE words SET meaning='의지, 원기', example_zh='他有着远大的志气，立志改变世界。', example_ko='그는 원대한 의지가 있어서 세상을 바꾸겠다는 뜻을 세웠다.' WHERE id=4591;",
    "UPDATE words SET meaning='충성하다', example_zh='他对公司忠诚，多年如一日地努力工作。', example_ko='그는 회사에 충성해서 수년 동안 하루같이 열심히 일했다.' WHERE id=4592;",
    "UPDATE words SET meaning='충실하다', example_zh='他忠实地记录了历史的每一个细节。', example_ko='그는 역사의 모든 세부 사항을 충실하게 기록했다.' WHERE id=4593;",
    "UPDATE words SET meaning='종점', example_zh='这条地铁线的终点是机场。', example_ko='이 지하철 노선의 종점은 공항이다.' WHERE id=4594;",
    "UPDATE words SET meaning='결국', example_zh='他的努力终究有了回报，取得了成功。', example_ko='그의 노력은 결국 보상을 받아서 성공을 거뒀다.' WHERE id=4595;",
    "UPDATE words SET meaning='평생', example_zh='他为教育事业奋斗了终年。', example_ko='그는 교육 사업을 위해 평생 분투했다.' WHERE id=4596;",
    "UPDATE words SET meaning='평생', example_zh='他终身致力于科学研究，为人类做出了重要贡献。', example_ko='그는 평생 과학 연구에 힘써서 인류에게 중요한 공헌을 했다.' WHERE id=4597;",
    "UPDATE words SET meaning='종료하다', example_zh='双方协议终止了合同关系。', example_ko='양측 협의로 계약 관계가 종료되었다.' WHERE id=4598;",
    "UPDATE words SET meaning='중단되다', example_zh='由于技术问题，网络中断了几个小时。', example_ko='기술 문제로 인터넷이 몇 시간 동안 중단되었다.' WHERE id=4599;",
    "UPDATE words SET meaning='중립', example_zh='在这场争论中，他保持了中立立场。', example_ko='이 논쟁에서 그는 중립 입장을 유지했다.' WHERE id=4600;",
    "UPDATE words SET meaning='중앙', example_zh='这个问题需要中央政府来处理。', example_ko='이 문제는 중앙 정부가 처리해야 한다.' WHERE id=4601;",
    "UPDATE words SET meaning='충심으로', example_zh='他衷心感谢大家的支持和帮助。', example_ko='그는 모두의 지지와 도움에 충심으로 감사한다.' WHERE id=4602;",
    "UPDATE words SET meaning='씨앗', example_zh='农民播下了种子，期待着丰收。', example_ko='농부가 씨앗을 뿌리고 풍년을 기대하고 있다.' WHERE id=4603;",
    "UPDATE words SET meaning='종족', example_zh='这个地区生活着多个不同的种族。', example_ko='이 지역에는 여러 다른 종족이 살고 있다.' WHERE id=4604;",
    "UPDATE words SET meaning='종양', example_zh='医生发现了他身体里有一个肿瘤。', example_ko='의사가 그의 몸에 종양이 있다는 것을 발견했다.' WHERE id=4605;",
    "UPDATE words SET meaning='중심', example_zh='他是团队的重心，大家都依靠他。', example_ko='그는 팀의 중심으로 모두가 그에게 의지한다.' WHERE id=4606;",
    "UPDATE words SET meaning='다 알고 있다', example_zh='这件事众所周知，没有必要再解释了。', example_ko='이 일은 모두가 다 알고 있어서 다시 설명할 필요가 없다.' WHERE id=4607;",
    "UPDATE words SET meaning='주, 지역', example_zh='美国有五十个州，各有其独特的文化。', example_ko='미국에는 50개 주가 있어서 각각 독특한 문화가 있다.' WHERE id=4608;",
    "UPDATE words SET meaning='배', example_zh='古代的舟是一种简单的木制船只。', example_ko='고대의 배는 간단한 나무 선박이었다.' WHERE id=4609;",
    "UPDATE words SET meaning='죽', example_zh='生病时喝粥有助于消化。', example_ko='병이 났을 때 죽을 먹으면 소화에 도움이 된다.' WHERE id=4610;",
    "UPDATE words SET meaning='주변', example_zh='城市周边的发展也日益迅速。', example_ko='도시 주변의 발전도 나날이 빨라지고 있다.' WHERE id=4611;",
    "UPDATE words SET meaning='주밀하다', example_zh='他的计划非常周密，考虑了所有细节。', example_ko='그의 계획은 매우 주밀해서 모든 세부 사항을 고려했다.' WHERE id=4612;",
    "UPDATE words SET meaning='주년', example_zh='今年是建校一百周年，学校举办了庆典。', example_ko='올해가 개교 100주년이어서 학교가 기념 행사를 열었다.' WHERE id=4613;",
    "UPDATE words SET meaning='주기', example_zh='地球绕太阳一周的周期是一年。', example_ko='지구가 태양을 한 바퀴 도는 주기는 1년이다.' WHERE id=4614;",
    "UPDATE words SET meaning='우여곡절', example_zh='这个项目经历了很多周折，才最终完成。', example_ko='이 프로젝트는 많은 우여곡절을 거쳐서 결국 완성되었다.' WHERE id=4615;",
    "UPDATE words SET meaning='주전하다, 자금이 원활하다', example_zh='公司的资金周转出现了问题。', example_ko='회사의 자금 주전에 문제가 생겼다.' WHERE id=4616;",
    "UPDATE words SET meaning='주름', example_zh='岁月在她脸上留下了皱纹。', example_ko='세월이 그녀의 얼굴에 주름을 남겼다.' WHERE id=4617;",
    "UPDATE words SET meaning='밤낮', example_zh='工人们昼夜不停地工作，终于完成了任务。', example_ko='노동자들이 밤낮없이 일해서 결국 임무를 완수했다.' WHERE id=4618;",
    "UPDATE words SET meaning='(그루를 세는 단위) 그루', example_zh='院子里种了几株梅花树。', example_ko='마당에 매화나무 몇 그루를 심었다.' WHERE id=4619;",
    "UPDATE words SET meaning='여러분', example_zh='诸位请注意，会议即将开始。', example_ko='여러분 주목해 주세요, 회의가 곧 시작됩니다.' WHERE id=4620;",
    "UPDATE words SET meaning='해마다', example_zh='这个地区的经济逐年增长。', example_ko='이 지역의 경제가 해마다 성장하고 있다.' WHERE id=4621;",
    "UPDATE words SET meaning='짚다, 기대다', example_zh='他拄着拐杖慢慢地走着。', example_ko='그는 지팡이를 짚고 천천히 걷고 있다.' WHERE id=4622;",
    "UPDATE words SET meaning='주최하다', example_zh='这次活动由政府主办，规模很大。', example_ko='이번 활동은 정부가 주최해서 규모가 매우 크다.' WHERE id=4623;",
    "UPDATE words SET meaning='주도하다', example_zh='他在项目中起到了主导作用。', example_ko='그는 프로젝트에서 주도적인 역할을 했다.' WHERE id=4624;",
    "UPDATE words SET meaning='주관하다', example_zh='他主管公司的财务部门。', example_ko='그는 회사의 재무 부서를 주관한다.' WHERE id=4625;",
    "UPDATE words SET meaning='주류', example_zh='这种观点逐渐成为了社会的主流思想。', example_ko='이 관점이 점차 사회의 주류 사상이 되었다.' WHERE id=4626;",
    "UPDATE words SET meaning='주권', example_zh='国家主权不容侵犯。', example_ko='국가 주권은 침범될 수 없다.' WHERE id=4627;",
    "UPDATE words SET meaning='주제', example_zh='这次会议的主题是环境保护。', example_ko='이번 회의의 주제는 환경 보호다.' WHERE id=4628;",
    "UPDATE words SET meaning='주택', example_zh='政府加大了对公共住宅的投入。', example_ko='정부가 공공 주택에 대한 투자를 늘렸다.' WHERE id=4629;",
    "UPDATE words SET meaning='주사하다', example_zh='医生给病人注射了镇痛剂。', example_ko='의사가 환자에게 진통제를 주사했다.' WHERE id=4630;",
    "UPDATE words SET meaning='주시하다', example_zh='他注视着窗外的风景，陷入了沉思。', example_ko='그는 창밖의 풍경을 주시하며 깊은 생각에 빠졌다.' WHERE id=4631;",
    "UPDATE words SET meaning='주석, 해설', example_zh='这本书的注释非常详细，帮助读者理解。', example_ko='이 책의 주석이 매우 상세해서 독자들이 이해하는 데 도움이 된다.' WHERE id=4632;",
    "UPDATE words SET meaning='중시하다', example_zh='他非常注重工作质量，不允许有任何失误。', example_ko='그는 업무 품질을 매우 중시해서 어떤 실수도 허용하지 않는다.' WHERE id=4633;",
    "UPDATE words SET meaning='조수, 보조원', example_zh='他担任了主编的助理，负责审稿工作。', example_ko='그는 주편의 조수를 맡아 심사 업무를 담당한다.' WHERE id=4634;",
    "UPDATE words SET meaning='조수', example_zh='他的助手非常能干，帮他处理了很多事务。', example_ko='그의 조수는 매우 유능해서 많은 업무를 처리하는 데 도움을 주었다.' WHERE id=4635;",
    "UPDATE words SET meaning='저작', example_zh='他的著作被翻译成了多国语言。', example_ko='그의 저작이 여러 나라 언어로 번역되었다.' WHERE id=4636;",
    "UPDATE words SET meaning='주둔하다', example_zh='军队驻扎在边境地区，保卫国家安全。', example_ko='군대가 국경 지역에 주둔하여 국가 안전을 수호하고 있다.' WHERE id=4637;",
    "UPDATE words SET meaning='주조하다', example_zh='这枚硬币是用铜铸造的。', example_ko='이 동전은 구리로 주조된 것이다.' WHERE id=4638;",
    "UPDATE words SET meaning='잡아당기다', example_zh='他拽住了绳子，用力往上拉。', example_ko='그는 밧줄을 잡아당겨 힘껏 위로 당겼다.' WHERE id=4639;",
    "UPDATE words SET meaning='전문 특기', example_zh='她的专长是钢琴演奏。', example_ko='그녀의 전문 특기는 피아노 연주다.' WHERE id=4640;",
    "UPDATE words SET meaning='특별히 오다', example_zh='他专程从北京赶来参加这次会议。', example_ko='그는 이번 회의에 참가하기 위해 특별히 베이징에서 왔다.' WHERE id=4641;",
    "UPDATE words SET meaning='전문학교, 2년제 대학', example_zh='他毕业于专科学校，后来继续深造。', example_ko='그는 전문학교를 졸업한 후 계속 깊이 공부했다.' WHERE id=4642;",
    "UPDATE words SET meaning='특허', example_zh='这项技术已经申请了专利保护。', example_ko='이 기술은 이미 특허 보호를 신청했다.' WHERE id=4643;",
    "UPDATE words SET meaning='전문 주제', example_zh='这次讨论会的专题是气候变化。', example_ko='이번 토론회의 전문 주제는 기후 변화다.' WHERE id=4644;",
    "UPDATE words SET meaning='벽돌', example_zh='这座房子是用砖瓦建造的。', example_ko='이 집은 벽돌로 지어진 것이다.' WHERE id=4645;",
    "UPDATE words SET meaning='전달하다', example_zh='请把我的问候转达给他。', example_ko='그에게 내 안부를 전달해 주세요.' WHERE id=4646;",
    "UPDATE words SET meaning='양도하다', example_zh='他将房子转让给了弟弟。', example_ko='그는 집을 남동생에게 양도했다.' WHERE id=4647;",
    "UPDATE words SET meaning='이동하다, 전환하다', example_zh='工厂将部分生产线转移到了农村。', example_ko='공장이 일부 생산 라인을 농촌으로 이전했다.' WHERE id=4648;",
    "UPDATE words SET meaning='전환, 전기', example_zh='这次谈判是关系的重要转折点。', example_ko='이번 협상은 관계의 중요한 전환점이다.' WHERE id=4649;",
    "UPDATE words SET meaning='전기', example_zh='这本书是关于他一生的传记。', example_ko='이 책은 그의 일생에 관한 전기다.' WHERE id=4650;",
    "UPDATE words SET meaning='장비하다', example_zh='军队装备了先进的武器和通信设备。', example_ko='군대가 첨단 무기와 통신 장비를 장비했다.' WHERE id=4651;",
    "UPDATE words SET meaning='장착하다, 하역하다', example_zh='工人们负责货物的装卸工作。', example_ko='노동자들이 화물의 장착 및 하역 작업을 담당한다.' WHERE id=4652;",
    "UPDATE words SET meaning='장엄하다', example_zh='这次典礼庄严肃穆，令人感动。', example_ko='이번 의식은 장엄하고 엄숙해서 감동적이다.' WHERE id=4653;",
    "UPDATE words SET meaning='진지하다, 점잖다', example_zh='他举止庄重，给人留下了深刻印象。', example_ko='그의 행동이 진지해서 깊은 인상을 남겼다.' WHERE id=4654;",
    "UPDATE words SET meaning='(건물을 세는 단위) 채', example_zh='他买了一幢别墅。', example_ko='그는 별장 한 채를 샀다.' WHERE id=4655;",
    "UPDATE words SET meaning='장관이다', example_zh='这片沙漠的日落景色十分壮观。', example_ko='이 사막의 석양 경치는 매우 장관이다.' WHERE id=4656;",
    "UPDATE words SET meaning='웅장하고 아름답다', example_zh='长城的壮丽风光吸引了无数游客。', example_ko='만리장성의 웅장하고 아름다운 경치가 수많은 관광객을 끌어들인다.' WHERE id=4657;",
    "UPDATE words SET meaning='장렬하다', example_zh='他在战场上壮烈牺牲，成为了英雄。', example_ko='그는 전장에서 장렬하게 희생되어 영웅이 되었다.' WHERE id=4658;",
    "UPDATE words SET meaning='추도하다', example_zh='人们聚集在一起，追悼了牺牲的英雄。', example_ko='사람들이 모여 희생된 영웅들을 추도했다.' WHERE id=4659;",
    "UPDATE words SET meaning='추구하다, 규명하다', example_zh='警察决定追究这件事的真相。', example_ko='경찰이 이 사건의 진상을 규명하기로 결정했다.' WHERE id=4660;",
    "UPDATE words SET meaning='준칙, 기준', example_zh='他做事总是遵守职业准则。', example_ko='그는 일할 때 항상 직업 준칙을 준수한다.' WHERE id=4661;",
    "UPDATE words SET meaning='연구하다, 생각하다', example_zh='他反复琢磨这个问题，终于找到了答案。', example_ko='그는 이 문제를 거듭 생각해서 결국 답을 찾았다.' WHERE id=4662;",
    "UPDATE words SET meaning='착수하다', example_zh='他着手解决了公司面临的主要问题。', example_ko='그는 회사가 직면한 주요 문제를 해결하는 데 착수했다.' WHERE id=4663;",
    "UPDATE words SET meaning='~를 위해 생각하다', example_zh='他总是为他人着想，从不考虑自己的利益。', example_ko='그는 항상 다른 사람을 위해 생각하며 자신의 이익을 고려하지 않는다.' WHERE id=4664;",
    "UPDATE words SET meaning='중점을 두다', example_zh='这次讨论着重分析了经济发展的原因。', example_ko='이번 토론은 경제 발전의 원인 분석에 중점을 두었다.' WHERE id=4665;",
    "UPDATE words SET meaning='탁월하다', example_zh='他在数学领域取得了卓越的成就。', example_ko='그는 수학 분야에서 탁월한 성취를 이루었다.' WHERE id=4666;",
    "UPDATE words SET meaning='자본', example_zh='这家公司的资本非常雄厚。', example_ko='이 회사의 자본은 매우 풍부하다.' WHERE id=4667;",
    "UPDATE words SET meaning='자산', example_zh='知识是最宝贵的无形资产。', example_ko='지식은 가장 소중한 무형 자산이다.' WHERE id=4668;",
    "UPDATE words SET meaning='자격이 깊다', example_zh='他是公司里资深的工程师，经验丰富。', example_ko='그는 회사에서 자격이 깊은 엔지니어로 경험이 풍부하다.' WHERE id=4669;",
    "UPDATE words SET meaning='자금을 지원하다', example_zh='政府资助了这项科研项目。', example_ko='정부가 이 과학 연구 프로젝트에 자금을 지원했다.' WHERE id=4670;",
    "UPDATE words SET meaning='자세, 태도', example_zh='他的姿态优雅，给人留下了良好的印象。', example_ko='그의 자세가 우아해서 좋은 인상을 남겼다.' WHERE id=4671;",
    "UPDATE words SET meaning='맛', example_zh='这道菜的滋味非常鲜美，让人回味无穷。', example_ko='이 요리의 맛은 매우 신선하고 맛있어서 두고두고 생각난다.' WHERE id=4672;",
    "UPDATE words SET meaning='자라다, 생겨나다', example_zh='腐败行为在这个地区滋长，需要坚决打击。', example_ko='이 지역에서 부패 행위가 자라나고 있어서 단호하게 단속해야 한다.' WHERE id=4673;",
    "UPDATE words SET meaning='총알, 탄환', example_zh='警察向逃跑的犯罪分子开枪，打出了子弹。', example_ko='경찰이 도주하는 범죄자에게 총을 쏴 탄환을 발사했다.' WHERE id=4674;",
    "UPDATE words SET meaning='알파벳', example_zh='英语字母共有二十六个。', example_ko='영어 알파벳은 총 26개다.' WHERE id=4675;",
    "UPDATE words SET meaning='자격지심이 있다', example_zh='他因为家庭背景而感到自卑。', example_ko='그는 가정 배경 때문에 자격지심을 느낀다.' WHERE id=4676;",
    "UPDATE words SET meaning='자발적이다', example_zh='他自发地组织了一次慈善活动。', example_ko='그는 자발적으로 자선 활동을 조직했다.' WHERE id=4677;",
    "UPDATE words SET meaning='자력갱생하다', example_zh='他从来不依赖他人，坚持自力更生。', example_ko='그는 타인에게 의존하지 않고 자력갱생하는 것을 고수한다.' WHERE id=4678;",
    "UPDATE words SET meaning='자만하다', example_zh='他取得了一点成绩就自满，停止了进步。', example_ko='그는 약간의 성적을 거두고 자만해서 발전을 멈추었다.' WHERE id=4679;",
    "UPDATE words SET meaning='자주적이다', example_zh='国家主张自主，不允许外国干涉内政。', example_ko='국가는 자주를 주장하며 외국이 내정에 간섭하는 것을 허용하지 않는다.' WHERE id=4680;",
    "UPDATE words SET meaning='자취, 흔적', example_zh='时间流逝，但当年的踪迹还留着。', example_ko='시간이 흘렀지만 그 당시의 자취가 아직 남아 있다.' WHERE id=4681;",
    "UPDATE words SET meaning='종지, 목적', example_zh='这个组织的宗旨是促进国际文化交流。', example_ko='이 조직의 종지는 국제 문화 교류를 촉진하는 것이다.' WHERE id=4682;",
    "UPDATE words SET meaning='갈색', example_zh='他穿着一件棕色的外套，看起来很精神。', example_ko='그는 갈색 외투를 입으니 매우 말끔해 보인다.' WHERE id=4683;",
    "UPDATE words SET meaning='요컨대', example_zh='总而言之，这个方案是可行的。', example_ko='요컨대 이 방안은 실행 가능하다.' WHERE id=4684;",
    "UPDATE words SET meaning='합계', example_zh='所有费用的总和超过了预算。', example_ko='모든 비용의 합계가 예산을 초과했다.' WHERE id=4685;",
    "UPDATE words SET meaning='종횡, 縦橫', example_zh='他纵横商场多年，积累了丰富的经验。', example_ko='그는 수년간 상업계를 종횡하며 풍부한 경험을 쌓았다.' WHERE id=4686;",
    "UPDATE words SET meaning='복도', example_zh='学校里的走廊宽敞明亮。', example_ko='학교의 복도는 넓고 밝다.' WHERE id=4687;",
    "UPDATE words SET meaning='새다, 누출하다', example_zh='机密信息走漏了出去，引发了严重后果。', example_ko='기밀 정보가 누출되어서 심각한 결과를 초래했다.' WHERE id=4688;",
    "UPDATE words SET meaning='밀수하다', example_zh='他因走私被海关查获，受到了严厉处罚。', example_ko='그는 밀수로 세관에 적발되어 엄한 처벌을 받았다.' WHERE id=4689;",
    "UPDATE words SET meaning='두들겨 패다', example_zh='他因口角而与人揍打，受到了法律制裁。', example_ko='그는 말다툼으로 사람을 두들겨 패서 법적 제재를 받았다.' WHERE id=4690;",
    "UPDATE words SET meaning='임대하다', example_zh='他租赁了一个办公室，开始了创业之路。', example_ko='그는 사무실을 임대해서 창업의 길을 시작했다.' WHERE id=4691;",
    "UPDATE words SET meaning='~에 족하다', example_zh='他的能力足以胜任这项工作。', example_ko='그의 능력은 이 업무를 충분히 감당할 수 있다.' WHERE id=4692;",
    "UPDATE words SET meaning='조, 그룹', example_zh='这个项目分成了三个组，各负责不同的任务。', example_ko='이 프로젝트는 세 조로 나뉘어 각각 다른 임무를 담당한다.' WHERE id=4693;",
    "UPDATE words SET meaning='저해하다', example_zh='不合理的制度阻碍了创新的发展。', example_ko='불합리한 제도가 혁신 발전을 저해했다.' WHERE id=4694;",
    "UPDATE words SET meaning='가로막다', example_zh='他们试图阻拦警察进入现场。', example_ko='그들은 경찰이 현장에 들어오는 것을 가로막으려 했다.' WHERE id=4695;",
    "UPDATE words SET meaning='방해하다, 저지하다', example_zh='他不断阻挠这项计划的实施。', example_ko='그는 끊임없이 이 계획의 실시를 방해했다.' WHERE id=4696;",
    "UPDATE words SET meaning='할아버지', example_zh='他的祖父是一位受人尊敬的学者。', example_ko='그의 할아버지는 존경받는 학자다.' WHERE id=4697;",
    "UPDATE words SET meaning='파고들어 연구하다', example_zh='他钻研了多年，终于掌握了这门技术。', example_ko='그는 수년간 파고들어 연구해서 결국 이 기술을 습득했다.' WHERE id=4698;",
    "UPDATE words SET meaning='다이아몬드', example_zh='这枚戒指上镶嵌着一颗大钻石。', example_ko='이 반지에는 큰 다이아몬드 하나가 박혀 있다.' WHERE id=4699;",
    "UPDATE words SET meaning='입술', example_zh='她涂了一层口红，嘴唇显得格外红润。', example_ko='그녀는 립스틱을 바르니 입술이 특히 붉고 윤기가 난다.' WHERE id=4700;",
    "UPDATE words SET meaning='존엄', example_zh='每个人都有维护自己尊严的权利。', example_ko='모든 사람은 자신의 존엄을 지킬 권리가 있다.' WHERE id=4701;",
    "UPDATE words SET meaning='따르다', example_zh='他遵循了老师的建议，取得了很大的进步。', example_ko='그는 선생님의 건의를 따르며 많은 발전을 이루었다.' WHERE id=4702;",
    "UPDATE words SET meaning='좌우하다, 대략', example_zh='他的决定左右了整个项目的发展方向。', example_ko='그의 결정이 프로젝트 전체의 발전 방향을 좌우했다.' WHERE id=4703;",
    "UPDATE words SET meaning='한턱내다', example_zh='他赢得了比赛，决定做东请大家吃饭。', example_ko='그는 대회에서 이겨서 모두에게 한턱 내기로 결정했다.' WHERE id=4704;",
    "UPDATE words SET meaning='결정하다, 주관하다', example_zh='他做主同意了这个提案。', example_ko='그가 직접 결정해서 이 제안에 동의했다.' WHERE id=4705;",
    "UPDATE words SET meaning='좌우명', example_zh='他的座右铭是勤奋、诚实、善良。', example_ko='그의 좌우명은 근면, 정직, 선량이다.' WHERE id=4706;",
    "UPDATE words SET meaning='부정행위를 하다', example_zh='考试作弊是不道德的行为，会受到严厉处罚。', example_ko='시험에서 부정행위를 하는 것은 비도덕적인 행동으로 엄한 처벌을 받는다.' WHERE id=4707;",
    "UPDATE words SET meaning='무효가 되다', example_zh='由于超过了有效期，这张票已经作废。', example_ko='유효 기간이 지나서 이 표는 이미 무효가 되었다.' WHERE id=4708;",
    "UPDATE words SET meaning='작풍, 업무 방식', example_zh='这位领导的作风非常务实，受到了大家的好评。', example_ko='이 지도자의 작풍은 매우 실무적이어서 모두의 호평을 받았다.' WHERE id=4709;",
    "UPDATE words SET meaning='작식, 일하고 쉬는 시간', example_zh='良好的作息习惯对健康非常重要。', example_ko='좋은 작식 습관은 건강에 매우 중요하다.' WHERE id=4710;",
]

with open('hsk6_data_4.sql', 'a', encoding='utf-8') as f:
    for line in lines:
        f.write(line + '\n')

print(f'Done, appended {len(lines)} lines')
